/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findDisputeConfigPda } from "../pdas";
import { STAYKE_DISPUTES_PROGRAM_ADDRESS } from "../programs";

export const ADD_ADMIN_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  177, 236, 33, 205, 124, 152, 55, 186,
]);

export function getAddAdminDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(ADD_ADMIN_DISCRIMINATOR);
}

export type AddAdminInstruction<
  TProgram extends string = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountDisputeConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountDisputeConfig extends string
        ? WritableAccount<TAccountDisputeConfig>
        : TAccountDisputeConfig,
      ...TRemainingAccounts,
    ]
  >;

export type AddAdminInstructionData = {
  discriminator: ReadonlyUint8Array;
  admin: Address;
};

export type AddAdminInstructionDataArgs = { admin: Address };

export function getAddAdminInstructionDataEncoder(): FixedSizeEncoder<AddAdminInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["admin", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: ADD_ADMIN_DISCRIMINATOR }),
  );
}

export function getAddAdminInstructionDataDecoder(): FixedSizeDecoder<AddAdminInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["admin", getAddressDecoder()],
  ]);
}

export function getAddAdminInstructionDataCodec(): FixedSizeCodec<
  AddAdminInstructionDataArgs,
  AddAdminInstructionData
> {
  return combineCodec(
    getAddAdminInstructionDataEncoder(),
    getAddAdminInstructionDataDecoder(),
  );
}

export type AddAdminAsyncInput<
  TAccountAdmin extends string = string,
  TAccountDisputeConfig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  disputeConfig?: Address<TAccountDisputeConfig>;
  adminArg: AddAdminInstructionDataArgs["admin"];
};

export async function getAddAdminInstructionAsync<
  TAccountAdmin extends string,
  TAccountDisputeConfig extends string,
  TProgramAddress extends Address = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
>(
  input: AddAdminAsyncInput<TAccountAdmin, TAccountDisputeConfig>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AddAdminInstruction<TProgramAddress, TAccountAdmin, TAccountDisputeConfig>
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_DISPUTES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    disputeConfig: { value: input.disputeConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input, admin: input.adminArg };

  // Resolve default values.
  if (!accounts.disputeConfig.value) {
    accounts.disputeConfig.value = await findDisputeConfigPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("disputeConfig", accounts.disputeConfig),
    ],
    data: getAddAdminInstructionDataEncoder().encode(
      args as AddAdminInstructionDataArgs,
    ),
    programAddress,
  } as AddAdminInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountDisputeConfig
  >);
}

export type AddAdminInput<
  TAccountAdmin extends string = string,
  TAccountDisputeConfig extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  disputeConfig: Address<TAccountDisputeConfig>;
  adminArg: AddAdminInstructionDataArgs["admin"];
};

export function getAddAdminInstruction<
  TAccountAdmin extends string,
  TAccountDisputeConfig extends string,
  TProgramAddress extends Address = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
>(
  input: AddAdminInput<TAccountAdmin, TAccountDisputeConfig>,
  config?: { programAddress?: TProgramAddress },
): AddAdminInstruction<TProgramAddress, TAccountAdmin, TAccountDisputeConfig> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_DISPUTES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    disputeConfig: { value: input.disputeConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input, admin: input.adminArg };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("disputeConfig", accounts.disputeConfig),
    ],
    data: getAddAdminInstructionDataEncoder().encode(
      args as AddAdminInstructionDataArgs,
    ),
    programAddress,
  } as AddAdminInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountDisputeConfig
  >);
}

export type ParsedAddAdminInstruction<
  TProgram extends string = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    disputeConfig: TAccountMetas[1];
  };
  data: AddAdminInstructionData;
};

export function parseAddAdminInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAddAdminInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { admin: getNextAccount(), disputeConfig: getNextAccount() },
    data: getAddAdminInstructionDataDecoder().decode(instruction.data),
  };
}
