/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findConfigPda,
  findCpiAuthorityPda,
  findTreasuryConfigPda,
} from "../pdas";
import { STAYKE_DISPUTES_PROGRAM_ADDRESS } from "../programs";
import {
  getPenaltySeverityDecoder,
  getPenaltySeverityEncoder,
  type PenaltySeverity,
  type PenaltySeverityArgs,
} from "../types";

export const PENALIZE_USER_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  4, 118, 74, 208, 212, 28, 119, 50,
]);

export function getPenalizeUserDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PENALIZE_USER_DISCRIMINATOR,
  );
}

export type PenalizeUserInstruction<
  TProgram extends string = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountPenalizedUserProfile extends string | AccountMeta<string> = string,
  TAccountPenalizedReputationProfile extends string | AccountMeta<string> =
    string,
  TAccountAffectedTokenAccount extends string | AccountMeta<string> = string,
  TAccountAffectedWallet extends string | AccountMeta<string> = string,
  TAccountTreasuryConfig extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountTreasuryVault extends string | AccountMeta<string> = string,
  TAccountTreasuryPda extends string | AccountMeta<string> = string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TAccountStaykeCoreProgram extends string | AccountMeta<string> =
    "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm",
  TAccountStaykeTreasuryProgram extends string | AccountMeta<string> =
    "HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountPenalizedUserProfile extends string
        ? WritableAccount<TAccountPenalizedUserProfile>
        : TAccountPenalizedUserProfile,
      TAccountPenalizedReputationProfile extends string
        ? WritableAccount<TAccountPenalizedReputationProfile>
        : TAccountPenalizedReputationProfile,
      TAccountAffectedTokenAccount extends string
        ? WritableAccount<TAccountAffectedTokenAccount>
        : TAccountAffectedTokenAccount,
      TAccountAffectedWallet extends string
        ? ReadonlyAccount<TAccountAffectedWallet>
        : TAccountAffectedWallet,
      TAccountTreasuryConfig extends string
        ? ReadonlyAccount<TAccountTreasuryConfig>
        : TAccountTreasuryConfig,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountTreasuryVault extends string
        ? WritableAccount<TAccountTreasuryVault>
        : TAccountTreasuryVault,
      TAccountTreasuryPda extends string
        ? ReadonlyAccount<TAccountTreasuryPda>
        : TAccountTreasuryPda,
      TAccountUsdcMint extends string
        ? WritableAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountCpiAuthority extends string
        ? ReadonlyAccount<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      TAccountStaykeCoreProgram extends string
        ? ReadonlyAccount<TAccountStaykeCoreProgram>
        : TAccountStaykeCoreProgram,
      TAccountStaykeTreasuryProgram extends string
        ? ReadonlyAccount<TAccountStaykeTreasuryProgram>
        : TAccountStaykeTreasuryProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PenalizeUserInstructionData = {
  discriminator: ReadonlyUint8Array;
  severity: PenaltySeverity;
};

export type PenalizeUserInstructionDataArgs = { severity: PenaltySeverityArgs };

export function getPenalizeUserInstructionDataEncoder(): FixedSizeEncoder<PenalizeUserInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["severity", getPenaltySeverityEncoder()],
    ]),
    (value) => ({ ...value, discriminator: PENALIZE_USER_DISCRIMINATOR }),
  );
}

export function getPenalizeUserInstructionDataDecoder(): FixedSizeDecoder<PenalizeUserInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["severity", getPenaltySeverityDecoder()],
  ]);
}

export function getPenalizeUserInstructionDataCodec(): FixedSizeCodec<
  PenalizeUserInstructionDataArgs,
  PenalizeUserInstructionData
> {
  return combineCodec(
    getPenalizeUserInstructionDataEncoder(),
    getPenalizeUserInstructionDataDecoder(),
  );
}

export type PenalizeUserAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountPenalizedUserProfile extends string = string,
  TAccountPenalizedReputationProfile extends string = string,
  TAccountAffectedTokenAccount extends string = string,
  TAccountAffectedWallet extends string = string,
  TAccountTreasuryConfig extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountTreasuryVault extends string = string,
  TAccountTreasuryPda extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
  TAccountStaykeTreasuryProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config?: Address<TAccountConfig>;
  penalizedUserProfile: Address<TAccountPenalizedUserProfile>;
  penalizedReputationProfile: Address<TAccountPenalizedReputationProfile>;
  affectedTokenAccount: Address<TAccountAffectedTokenAccount>;
  affectedWallet: Address<TAccountAffectedWallet>;
  treasuryConfig?: Address<TAccountTreasuryConfig>;
  globalConfig?: Address<TAccountGlobalConfig>;
  treasuryVault: Address<TAccountTreasuryVault>;
  treasuryPda: Address<TAccountTreasuryPda>;
  usdcMint: Address<TAccountUsdcMint>;
  cpiAuthority?: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  staykeTreasuryProgram?: Address<TAccountStaykeTreasuryProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  severity: PenalizeUserInstructionDataArgs["severity"];
};

export async function getPenalizeUserInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountPenalizedUserProfile extends string,
  TAccountPenalizedReputationProfile extends string,
  TAccountAffectedTokenAccount extends string,
  TAccountAffectedWallet extends string,
  TAccountTreasuryConfig extends string,
  TAccountGlobalConfig extends string,
  TAccountTreasuryVault extends string,
  TAccountTreasuryPda extends string,
  TAccountUsdcMint extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TAccountStaykeTreasuryProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
>(
  input: PenalizeUserAsyncInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountPenalizedUserProfile,
    TAccountPenalizedReputationProfile,
    TAccountAffectedTokenAccount,
    TAccountAffectedWallet,
    TAccountTreasuryConfig,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountUsdcMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  PenalizeUserInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountPenalizedUserProfile,
    TAccountPenalizedReputationProfile,
    TAccountAffectedTokenAccount,
    TAccountAffectedWallet,
    TAccountTreasuryConfig,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountUsdcMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_DISPUTES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    penalizedUserProfile: {
      value: input.penalizedUserProfile ?? null,
      isWritable: true,
    },
    penalizedReputationProfile: {
      value: input.penalizedReputationProfile ?? null,
      isWritable: true,
    },
    affectedTokenAccount: {
      value: input.affectedTokenAccount ?? null,
      isWritable: true,
    },
    affectedWallet: { value: input.affectedWallet ?? null, isWritable: false },
    treasuryConfig: { value: input.treasuryConfig ?? null, isWritable: false },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    treasuryVault: { value: input.treasuryVault ?? null, isWritable: true },
    treasuryPda: { value: input.treasuryPda ?? null, isWritable: false },
    usdcMint: { value: input.usdcMint ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
    staykeTreasuryProgram: {
      value: input.staykeTreasuryProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.treasuryConfig.value) {
    accounts.treasuryConfig.value = await findTreasuryConfigPda();
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.cpiAuthority.value) {
    accounts.cpiAuthority.value = await findCpiAuthorityPda();
  }
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }
  if (!accounts.staykeTreasuryProgram.value) {
    accounts.staykeTreasuryProgram.value =
      "HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY" as Address<"HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("penalizedUserProfile", accounts.penalizedUserProfile),
      getAccountMeta(
        "penalizedReputationProfile",
        accounts.penalizedReputationProfile,
      ),
      getAccountMeta("affectedTokenAccount", accounts.affectedTokenAccount),
      getAccountMeta("affectedWallet", accounts.affectedWallet),
      getAccountMeta("treasuryConfig", accounts.treasuryConfig),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("treasuryVault", accounts.treasuryVault),
      getAccountMeta("treasuryPda", accounts.treasuryPda),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
      getAccountMeta("staykeTreasuryProgram", accounts.staykeTreasuryProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getPenalizeUserInstructionDataEncoder().encode(
      args as PenalizeUserInstructionDataArgs,
    ),
    programAddress,
  } as PenalizeUserInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountPenalizedUserProfile,
    TAccountPenalizedReputationProfile,
    TAccountAffectedTokenAccount,
    TAccountAffectedWallet,
    TAccountTreasuryConfig,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountUsdcMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >);
}

export type PenalizeUserInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountPenalizedUserProfile extends string = string,
  TAccountPenalizedReputationProfile extends string = string,
  TAccountAffectedTokenAccount extends string = string,
  TAccountAffectedWallet extends string = string,
  TAccountTreasuryConfig extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountTreasuryVault extends string = string,
  TAccountTreasuryPda extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
  TAccountStaykeTreasuryProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config: Address<TAccountConfig>;
  penalizedUserProfile: Address<TAccountPenalizedUserProfile>;
  penalizedReputationProfile: Address<TAccountPenalizedReputationProfile>;
  affectedTokenAccount: Address<TAccountAffectedTokenAccount>;
  affectedWallet: Address<TAccountAffectedWallet>;
  treasuryConfig: Address<TAccountTreasuryConfig>;
  globalConfig: Address<TAccountGlobalConfig>;
  treasuryVault: Address<TAccountTreasuryVault>;
  treasuryPda: Address<TAccountTreasuryPda>;
  usdcMint: Address<TAccountUsdcMint>;
  cpiAuthority: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  staykeTreasuryProgram?: Address<TAccountStaykeTreasuryProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  severity: PenalizeUserInstructionDataArgs["severity"];
};

export function getPenalizeUserInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountPenalizedUserProfile extends string,
  TAccountPenalizedReputationProfile extends string,
  TAccountAffectedTokenAccount extends string,
  TAccountAffectedWallet extends string,
  TAccountTreasuryConfig extends string,
  TAccountGlobalConfig extends string,
  TAccountTreasuryVault extends string,
  TAccountTreasuryPda extends string,
  TAccountUsdcMint extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TAccountStaykeTreasuryProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
>(
  input: PenalizeUserInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountPenalizedUserProfile,
    TAccountPenalizedReputationProfile,
    TAccountAffectedTokenAccount,
    TAccountAffectedWallet,
    TAccountTreasuryConfig,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountUsdcMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): PenalizeUserInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfig,
  TAccountPenalizedUserProfile,
  TAccountPenalizedReputationProfile,
  TAccountAffectedTokenAccount,
  TAccountAffectedWallet,
  TAccountTreasuryConfig,
  TAccountGlobalConfig,
  TAccountTreasuryVault,
  TAccountTreasuryPda,
  TAccountUsdcMint,
  TAccountCpiAuthority,
  TAccountStaykeCoreProgram,
  TAccountStaykeTreasuryProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_DISPUTES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    penalizedUserProfile: {
      value: input.penalizedUserProfile ?? null,
      isWritable: true,
    },
    penalizedReputationProfile: {
      value: input.penalizedReputationProfile ?? null,
      isWritable: true,
    },
    affectedTokenAccount: {
      value: input.affectedTokenAccount ?? null,
      isWritable: true,
    },
    affectedWallet: { value: input.affectedWallet ?? null, isWritable: false },
    treasuryConfig: { value: input.treasuryConfig ?? null, isWritable: false },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    treasuryVault: { value: input.treasuryVault ?? null, isWritable: true },
    treasuryPda: { value: input.treasuryPda ?? null, isWritable: false },
    usdcMint: { value: input.usdcMint ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
    staykeTreasuryProgram: {
      value: input.staykeTreasuryProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }
  if (!accounts.staykeTreasuryProgram.value) {
    accounts.staykeTreasuryProgram.value =
      "HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY" as Address<"HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("penalizedUserProfile", accounts.penalizedUserProfile),
      getAccountMeta(
        "penalizedReputationProfile",
        accounts.penalizedReputationProfile,
      ),
      getAccountMeta("affectedTokenAccount", accounts.affectedTokenAccount),
      getAccountMeta("affectedWallet", accounts.affectedWallet),
      getAccountMeta("treasuryConfig", accounts.treasuryConfig),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("treasuryVault", accounts.treasuryVault),
      getAccountMeta("treasuryPda", accounts.treasuryPda),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
      getAccountMeta("staykeTreasuryProgram", accounts.staykeTreasuryProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getPenalizeUserInstructionDataEncoder().encode(
      args as PenalizeUserInstructionDataArgs,
    ),
    programAddress,
  } as PenalizeUserInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountPenalizedUserProfile,
    TAccountPenalizedReputationProfile,
    TAccountAffectedTokenAccount,
    TAccountAffectedWallet,
    TAccountTreasuryConfig,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountUsdcMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >);
}

export type ParsedPenalizeUserInstruction<
  TProgram extends string = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    config: TAccountMetas[1];
    penalizedUserProfile: TAccountMetas[2];
    penalizedReputationProfile: TAccountMetas[3];
    affectedTokenAccount: TAccountMetas[4];
    affectedWallet: TAccountMetas[5];
    treasuryConfig: TAccountMetas[6];
    globalConfig: TAccountMetas[7];
    treasuryVault: TAccountMetas[8];
    treasuryPda: TAccountMetas[9];
    usdcMint: TAccountMetas[10];
    cpiAuthority: TAccountMetas[11];
    staykeCoreProgram: TAccountMetas[12];
    staykeTreasuryProgram: TAccountMetas[13];
    tokenProgram: TAccountMetas[14];
  };
  data: PenalizeUserInstructionData;
};

export function parsePenalizeUserInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedPenalizeUserInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 15) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 15,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      config: getNextAccount(),
      penalizedUserProfile: getNextAccount(),
      penalizedReputationProfile: getNextAccount(),
      affectedTokenAccount: getNextAccount(),
      affectedWallet: getNextAccount(),
      treasuryConfig: getNextAccount(),
      globalConfig: getNextAccount(),
      treasuryVault: getNextAccount(),
      treasuryPda: getNextAccount(),
      usdcMint: getNextAccount(),
      cpiAuthority: getNextAccount(),
      staykeCoreProgram: getNextAccount(),
      staykeTreasuryProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getPenalizeUserInstructionDataDecoder().decode(instruction.data),
  };
}
