/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda, findCpiAuthorityPda, findDisputePda } from "../pdas";
import { STAYKE_DISPUTES_PROGRAM_ADDRESS } from "../programs";

export const RESOLVE_DISPUTE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array(
  [231, 6, 202, 6, 96, 103, 12, 230],
);

export function getResolveDisputeDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    RESOLVE_DISPUTE_DISCRIMINATOR,
  );
}

export type ResolveDisputeInstruction<
  TProgram extends string = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountDispute extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TAccountEscrowTokenAccount extends string | AccountMeta<string> = string,
  TAccountHostTokenAccount extends string | AccountMeta<string> = string,
  TAccountGuestTokenAccount extends string | AccountMeta<string> = string,
  TAccountPlatformVaultTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountStaykeEscrowProgram extends string | AccountMeta<string> =
    "68ipZiXiUhsaSYSqEM3619vXgKy5CqFmNE6rYzxrXu6a",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountDispute extends string
        ? WritableAccount<TAccountDispute>
        : TAccountDispute,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountCpiAuthority extends string
        ? ReadonlyAccount<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      TAccountEscrowTokenAccount extends string
        ? WritableAccount<TAccountEscrowTokenAccount>
        : TAccountEscrowTokenAccount,
      TAccountHostTokenAccount extends string
        ? WritableAccount<TAccountHostTokenAccount>
        : TAccountHostTokenAccount,
      TAccountGuestTokenAccount extends string
        ? WritableAccount<TAccountGuestTokenAccount>
        : TAccountGuestTokenAccount,
      TAccountPlatformVaultTokenAccount extends string
        ? WritableAccount<TAccountPlatformVaultTokenAccount>
        : TAccountPlatformVaultTokenAccount,
      TAccountUsdcMint extends string
        ? WritableAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountStaykeEscrowProgram extends string
        ? ReadonlyAccount<TAccountStaykeEscrowProgram>
        : TAccountStaykeEscrowProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ResolveDisputeInstructionData = {
  discriminator: ReadonlyUint8Array;
  hostShareBps: number;
  rejected: boolean;
};

export type ResolveDisputeInstructionDataArgs = {
  hostShareBps: number;
  rejected: boolean;
};

export function getResolveDisputeInstructionDataEncoder(): FixedSizeEncoder<ResolveDisputeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["hostShareBps", getU16Encoder()],
      ["rejected", getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: RESOLVE_DISPUTE_DISCRIMINATOR }),
  );
}

export function getResolveDisputeInstructionDataDecoder(): FixedSizeDecoder<ResolveDisputeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["hostShareBps", getU16Decoder()],
    ["rejected", getBooleanDecoder()],
  ]);
}

export function getResolveDisputeInstructionDataCodec(): FixedSizeCodec<
  ResolveDisputeInstructionDataArgs,
  ResolveDisputeInstructionData
> {
  return combineCodec(
    getResolveDisputeInstructionDataEncoder(),
    getResolveDisputeInstructionDataDecoder(),
  );
}

export type ResolveDisputeAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountDispute extends string = string,
  TAccountBooking extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountHostTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountPlatformVaultTokenAccount extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountStaykeEscrowProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config?: Address<TAccountConfig>;
  dispute?: Address<TAccountDispute>;
  booking: Address<TAccountBooking>;
  globalConfig?: Address<TAccountGlobalConfig>;
  cpiAuthority?: Address<TAccountCpiAuthority>;
  escrowTokenAccount: Address<TAccountEscrowTokenAccount>;
  hostTokenAccount: Address<TAccountHostTokenAccount>;
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  platformVaultTokenAccount: Address<TAccountPlatformVaultTokenAccount>;
  usdcMint: Address<TAccountUsdcMint>;
  staykeEscrowProgram?: Address<TAccountStaykeEscrowProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  hostShareBps: ResolveDisputeInstructionDataArgs["hostShareBps"];
  rejected: ResolveDisputeInstructionDataArgs["rejected"];
};

export async function getResolveDisputeInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountDispute extends string,
  TAccountBooking extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountHostTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountPlatformVaultTokenAccount extends string,
  TAccountUsdcMint extends string,
  TAccountStaykeEscrowProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
>(
  input: ResolveDisputeAsyncInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountDispute,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountGuestTokenAccount,
    TAccountPlatformVaultTokenAccount,
    TAccountUsdcMint,
    TAccountStaykeEscrowProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ResolveDisputeInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountDispute,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountGuestTokenAccount,
    TAccountPlatformVaultTokenAccount,
    TAccountUsdcMint,
    TAccountStaykeEscrowProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_DISPUTES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    dispute: { value: input.dispute ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    hostTokenAccount: {
      value: input.hostTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    platformVaultTokenAccount: {
      value: input.platformVaultTokenAccount ?? null,
      isWritable: true,
    },
    usdcMint: { value: input.usdcMint ?? null, isWritable: true },
    staykeEscrowProgram: {
      value: input.staykeEscrowProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.dispute.value) {
    accounts.dispute.value = await findDisputePda({
      booking: getAddressFromResolvedInstructionAccount(
        "booking",
        accounts.booking.value,
      ),
    });
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.cpiAuthority.value) {
    accounts.cpiAuthority.value = await findCpiAuthorityPda();
  }
  if (!accounts.staykeEscrowProgram.value) {
    accounts.staykeEscrowProgram.value =
      "68ipZiXiUhsaSYSqEM3619vXgKy5CqFmNE6rYzxrXu6a" as Address<"68ipZiXiUhsaSYSqEM3619vXgKy5CqFmNE6rYzxrXu6a">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("dispute", accounts.dispute),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("hostTokenAccount", accounts.hostTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta(
        "platformVaultTokenAccount",
        accounts.platformVaultTokenAccount,
      ),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("staykeEscrowProgram", accounts.staykeEscrowProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getResolveDisputeInstructionDataEncoder().encode(
      args as ResolveDisputeInstructionDataArgs,
    ),
    programAddress,
  } as ResolveDisputeInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountDispute,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountGuestTokenAccount,
    TAccountPlatformVaultTokenAccount,
    TAccountUsdcMint,
    TAccountStaykeEscrowProgram,
    TAccountTokenProgram
  >);
}

export type ResolveDisputeInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountDispute extends string = string,
  TAccountBooking extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountHostTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountPlatformVaultTokenAccount extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountStaykeEscrowProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config: Address<TAccountConfig>;
  dispute: Address<TAccountDispute>;
  booking: Address<TAccountBooking>;
  globalConfig: Address<TAccountGlobalConfig>;
  cpiAuthority: Address<TAccountCpiAuthority>;
  escrowTokenAccount: Address<TAccountEscrowTokenAccount>;
  hostTokenAccount: Address<TAccountHostTokenAccount>;
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  platformVaultTokenAccount: Address<TAccountPlatformVaultTokenAccount>;
  usdcMint: Address<TAccountUsdcMint>;
  staykeEscrowProgram?: Address<TAccountStaykeEscrowProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  hostShareBps: ResolveDisputeInstructionDataArgs["hostShareBps"];
  rejected: ResolveDisputeInstructionDataArgs["rejected"];
};

export function getResolveDisputeInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountDispute extends string,
  TAccountBooking extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountHostTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountPlatformVaultTokenAccount extends string,
  TAccountUsdcMint extends string,
  TAccountStaykeEscrowProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
>(
  input: ResolveDisputeInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountDispute,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountGuestTokenAccount,
    TAccountPlatformVaultTokenAccount,
    TAccountUsdcMint,
    TAccountStaykeEscrowProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ResolveDisputeInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfig,
  TAccountDispute,
  TAccountBooking,
  TAccountGlobalConfig,
  TAccountCpiAuthority,
  TAccountEscrowTokenAccount,
  TAccountHostTokenAccount,
  TAccountGuestTokenAccount,
  TAccountPlatformVaultTokenAccount,
  TAccountUsdcMint,
  TAccountStaykeEscrowProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_DISPUTES_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    dispute: { value: input.dispute ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    hostTokenAccount: {
      value: input.hostTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    platformVaultTokenAccount: {
      value: input.platformVaultTokenAccount ?? null,
      isWritable: true,
    },
    usdcMint: { value: input.usdcMint ?? null, isWritable: true },
    staykeEscrowProgram: {
      value: input.staykeEscrowProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.staykeEscrowProgram.value) {
    accounts.staykeEscrowProgram.value =
      "68ipZiXiUhsaSYSqEM3619vXgKy5CqFmNE6rYzxrXu6a" as Address<"68ipZiXiUhsaSYSqEM3619vXgKy5CqFmNE6rYzxrXu6a">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("dispute", accounts.dispute),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("hostTokenAccount", accounts.hostTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta(
        "platformVaultTokenAccount",
        accounts.platformVaultTokenAccount,
      ),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("staykeEscrowProgram", accounts.staykeEscrowProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getResolveDisputeInstructionDataEncoder().encode(
      args as ResolveDisputeInstructionDataArgs,
    ),
    programAddress,
  } as ResolveDisputeInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountDispute,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountGuestTokenAccount,
    TAccountPlatformVaultTokenAccount,
    TAccountUsdcMint,
    TAccountStaykeEscrowProgram,
    TAccountTokenProgram
  >);
}

export type ParsedResolveDisputeInstruction<
  TProgram extends string = typeof STAYKE_DISPUTES_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    config: TAccountMetas[1];
    dispute: TAccountMetas[2];
    booking: TAccountMetas[3];
    globalConfig: TAccountMetas[4];
    cpiAuthority: TAccountMetas[5];
    escrowTokenAccount: TAccountMetas[6];
    hostTokenAccount: TAccountMetas[7];
    guestTokenAccount: TAccountMetas[8];
    platformVaultTokenAccount: TAccountMetas[9];
    usdcMint: TAccountMetas[10];
    staykeEscrowProgram: TAccountMetas[11];
    tokenProgram: TAccountMetas[12];
  };
  data: ResolveDisputeInstructionData;
};

export function parseResolveDisputeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedResolveDisputeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 13) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 13,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      config: getNextAccount(),
      dispute: getNextAccount(),
      booking: getNextAccount(),
      globalConfig: getNextAccount(),
      cpiAuthority: getNextAccount(),
      escrowTokenAccount: getNextAccount(),
      hostTokenAccount: getNextAccount(),
      guestTokenAccount: getNextAccount(),
      platformVaultTokenAccount: getNextAccount(),
      usdcMint: getNextAccount(),
      staykeEscrowProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getResolveDisputeInstructionDataDecoder().decode(instruction.data),
  };
}
