/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const BOOKING_DAYS_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  134, 102, 203, 81, 137, 194, 64, 222,
]);

export function getBookingDaysDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    BOOKING_DAYS_DISCRIMINATOR,
  );
}

export type BookingDays = {
  discriminator: ReadonlyUint8Array;
  occupiedDays: Array<number>;
  year: number;
  bump: number;
};

export type BookingDaysArgs = {
  occupiedDays: Array<number>;
  year: number;
  bump: number;
};

/** Gets the encoder for {@link BookingDaysArgs} account data. */
export function getBookingDaysEncoder(): FixedSizeEncoder<BookingDaysArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["occupiedDays", getArrayEncoder(getU32Encoder(), { size: 12 })],
      ["year", getU32Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: BOOKING_DAYS_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link BookingDays} account data. */
export function getBookingDaysDecoder(): FixedSizeDecoder<BookingDays> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["occupiedDays", getArrayDecoder(getU32Decoder(), { size: 12 })],
    ["year", getU32Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link BookingDays} account data. */
export function getBookingDaysCodec(): FixedSizeCodec<
  BookingDaysArgs,
  BookingDays
> {
  return combineCodec(getBookingDaysEncoder(), getBookingDaysDecoder());
}

export function decodeBookingDays<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<BookingDays, TAddress>;
export function decodeBookingDays<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<BookingDays, TAddress>;
export function decodeBookingDays<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<BookingDays, TAddress> | MaybeAccount<BookingDays, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getBookingDaysDecoder(),
  );
}

export async function fetchBookingDays<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<BookingDays, TAddress>> {
  const maybeAccount = await fetchMaybeBookingDays(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeBookingDays<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<BookingDays, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeBookingDays(maybeAccount);
}

export async function fetchAllBookingDays(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<BookingDays>[]> {
  const maybeAccounts = await fetchAllMaybeBookingDays(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeBookingDays(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<BookingDays>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeBookingDays(maybeAccount));
}

export function getBookingDaysSize(): number {
  return 61;
}
