/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getBookingStatusDecoder,
  getBookingStatusEncoder,
  type BookingStatus,
  type BookingStatusArgs,
} from "../types";

export const BOOKING_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  147, 50, 61, 138, 208, 21, 254, 156,
]);

export function getBookingDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(BOOKING_DISCRIMINATOR);
}

export type Booking = {
  discriminator: ReadonlyUint8Array;
  /** Guest Pubkey */
  guest: Address;
  /** Host Pubkey */
  host: Address;
  /** Property pubkey */
  property: Address;
  /** Was money already deposited? */
  isDeposit: boolean;
  /** Check in as unix timestamp */
  checkIn: bigint;
  /** Check out as unix timestamp */
  checkOut: bigint;
  /** Total price by all nights */
  totalPrice: bigint;
  /** Booking Status */
  status: BookingStatus;
  /** Bump of the escrow token account PDA — needed to sign CPIs in complete_stay. */
  escrowBump: number;
  bump: number;
};

export type BookingArgs = {
  /** Guest Pubkey */
  guest: Address;
  /** Host Pubkey */
  host: Address;
  /** Property pubkey */
  property: Address;
  /** Was money already deposited? */
  isDeposit: boolean;
  /** Check in as unix timestamp */
  checkIn: number | bigint;
  /** Check out as unix timestamp */
  checkOut: number | bigint;
  /** Total price by all nights */
  totalPrice: number | bigint;
  /** Booking Status */
  status: BookingStatusArgs;
  /** Bump of the escrow token account PDA — needed to sign CPIs in complete_stay. */
  escrowBump: number;
  bump: number;
};

/** Gets the encoder for {@link BookingArgs} account data. */
export function getBookingEncoder(): FixedSizeEncoder<BookingArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["guest", getAddressEncoder()],
      ["host", getAddressEncoder()],
      ["property", getAddressEncoder()],
      ["isDeposit", getBooleanEncoder()],
      ["checkIn", getI64Encoder()],
      ["checkOut", getI64Encoder()],
      ["totalPrice", getU64Encoder()],
      ["status", getBookingStatusEncoder()],
      ["escrowBump", getU8Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: BOOKING_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Booking} account data. */
export function getBookingDecoder(): FixedSizeDecoder<Booking> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["guest", getAddressDecoder()],
    ["host", getAddressDecoder()],
    ["property", getAddressDecoder()],
    ["isDeposit", getBooleanDecoder()],
    ["checkIn", getI64Decoder()],
    ["checkOut", getI64Decoder()],
    ["totalPrice", getU64Decoder()],
    ["status", getBookingStatusDecoder()],
    ["escrowBump", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Booking} account data. */
export function getBookingCodec(): FixedSizeCodec<BookingArgs, Booking> {
  return combineCodec(getBookingEncoder(), getBookingDecoder());
}

export function decodeBooking<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Booking, TAddress>;
export function decodeBooking<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Booking, TAddress>;
export function decodeBooking<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Booking, TAddress> | MaybeAccount<Booking, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getBookingDecoder(),
  );
}

export async function fetchBooking<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Booking, TAddress>> {
  const maybeAccount = await fetchMaybeBooking(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeBooking<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Booking, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeBooking(maybeAccount);
}

export async function fetchAllBooking(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Booking>[]> {
  const maybeAccounts = await fetchAllMaybeBooking(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeBooking(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Booking>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeBooking(maybeAccount));
}

export function getBookingSize(): number {
  return 132;
}
