/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  extendClient,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithPayer,
  type ClientWithRpc,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  addSelfPlanAndSendFunctions,
  type SelfFetchFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/program-client-core";
import {
  getConfigAccCodec,
  getIdentityCodec,
  getListingCodec,
  getReputationProfileCodec,
  getUserProfileCodec,
  type ConfigAcc,
  type ConfigAccArgs,
  type Identity,
  type IdentityArgs,
  type Listing,
  type ListingArgs,
  type ReputationProfile,
  type ReputationProfileArgs,
  type UserProfile,
  type UserProfileArgs,
} from "../accounts";
import {
  getAddInfractionInstructionAsync,
  getClearActiveBookingInstructionAsync,
  getClearListingBookingInstructionAsync,
  getInitializeConfigInstructionAsync,
  getInitializeListingInstructionAsync,
  getInitializeUserProfileInstructionAsync,
  getInitIdentityInstructionAsync,
  getLinkIdentityInstructionAsync,
  getSetListingOccupiedInstructionAsync,
  getUpdateDepositInstructionAsync,
  getUpdateHostReviewInstructionAsync,
  getUpdateListingPriceInstructionAsync,
  getUpdateListingPublishInstructionAsync,
  getUpdateListingStateInstructionAsync,
  parseAddInfractionInstruction,
  parseClearActiveBookingInstruction,
  parseClearListingBookingInstruction,
  parseInitializeConfigInstruction,
  parseInitializeListingInstruction,
  parseInitializeUserProfileInstruction,
  parseInitIdentityInstruction,
  parseLinkIdentityInstruction,
  parseSetListingOccupiedInstruction,
  parseUpdateDepositInstruction,
  parseUpdateHostReviewInstruction,
  parseUpdateListingPriceInstruction,
  parseUpdateListingPublishInstruction,
  parseUpdateListingStateInstruction,
  type AddInfractionAsyncInput,
  type ClearActiveBookingAsyncInput,
  type ClearListingBookingAsyncInput,
  type InitializeConfigAsyncInput,
  type InitializeListingAsyncInput,
  type InitializeUserProfileAsyncInput,
  type InitIdentityAsyncInput,
  type LinkIdentityAsyncInput,
  type ParsedAddInfractionInstruction,
  type ParsedClearActiveBookingInstruction,
  type ParsedClearListingBookingInstruction,
  type ParsedInitializeConfigInstruction,
  type ParsedInitializeListingInstruction,
  type ParsedInitializeUserProfileInstruction,
  type ParsedInitIdentityInstruction,
  type ParsedLinkIdentityInstruction,
  type ParsedSetListingOccupiedInstruction,
  type ParsedUpdateDepositInstruction,
  type ParsedUpdateHostReviewInstruction,
  type ParsedUpdateListingPriceInstruction,
  type ParsedUpdateListingPublishInstruction,
  type ParsedUpdateListingStateInstruction,
  type SetListingOccupiedAsyncInput,
  type UpdateDepositAsyncInput,
  type UpdateHostReviewAsyncInput,
  type UpdateListingPriceAsyncInput,
  type UpdateListingPublishAsyncInput,
  type UpdateListingStateAsyncInput,
} from "../instructions";
import {
  findConfigPda,
  findIdentityPda,
  findListingPda,
  findReputationProfilePda,
  findUserProfilePda,
} from "../pdas";

export const STAYKE_CORE_PROGRAM_ADDRESS =
  "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;

export enum StaykeCoreAccount {
  ConfigAcc,
  Identity,
  Listing,
  ReputationProfile,
  UserProfile,
}

export function identifyStaykeCoreAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): StaykeCoreAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([107, 39, 92, 214, 247, 156, 30, 126]),
      ),
      0,
    )
  ) {
    return StaykeCoreAccount.ConfigAcc;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([58, 132, 5, 12, 176, 164, 85, 112]),
      ),
      0,
    )
  ) {
    return StaykeCoreAccount.Identity;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([218, 32, 50, 73, 43, 134, 26, 58]),
      ),
      0,
    )
  ) {
    return StaykeCoreAccount.Listing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([73, 32, 193, 201, 177, 91, 104, 136]),
      ),
      0,
    )
  ) {
    return StaykeCoreAccount.ReputationProfile;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([32, 37, 119, 205, 179, 180, 13, 194]),
      ),
      0,
    )
  ) {
    return StaykeCoreAccount.UserProfile;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "staykeCore" },
  );
}

export enum StaykeCoreInstruction {
  AddInfraction,
  ClearActiveBooking,
  ClearListingBooking,
  InitIdentity,
  InitializeConfig,
  InitializeListing,
  InitializeUserProfile,
  LinkIdentity,
  SetListingOccupied,
  UpdateDeposit,
  UpdateHostReview,
  UpdateListingPrice,
  UpdateListingPublish,
  UpdateListingState,
}

export function identifyStaykeCoreInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): StaykeCoreInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([238, 116, 210, 154, 186, 175, 136, 151]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.AddInfraction;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([109, 41, 40, 136, 10, 34, 239, 89]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.ClearActiveBooking;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([115, 33, 218, 127, 147, 182, 108, 120]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.ClearListingBooking;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([56, 12, 37, 133, 27, 121, 5, 155]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.InitIdentity;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([208, 127, 21, 1, 194, 190, 196, 70]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.InitializeConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([170, 54, 135, 232, 166, 202, 75, 54]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.InitializeListing;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([192, 144, 204, 140, 113, 25, 59, 102]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.InitializeUserProfile;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 194, 103, 122, 161, 65, 174, 142]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.LinkIdentity;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([125, 76, 4, 13, 181, 116, 53, 167]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.SetListingOccupied;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([126, 116, 15, 164, 238, 179, 155, 59]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.UpdateDeposit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([103, 62, 206, 90, 68, 110, 101, 85]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.UpdateHostReview;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([103, 80, 184, 80, 159, 24, 94, 138]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.UpdateListingPrice;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([168, 202, 247, 130, 113, 8, 109, 99]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.UpdateListingPublish;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([54, 223, 116, 48, 168, 240, 133, 49]),
      ),
      0,
    )
  ) {
    return StaykeCoreInstruction.UpdateListingState;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "staykeCore" },
  );
}

export type ParsedStaykeCoreInstruction<
  TProgram extends string = "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm",
> =
  | ({
      instructionType: StaykeCoreInstruction.AddInfraction;
    } & ParsedAddInfractionInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.ClearActiveBooking;
    } & ParsedClearActiveBookingInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.ClearListingBooking;
    } & ParsedClearListingBookingInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.InitIdentity;
    } & ParsedInitIdentityInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.InitializeConfig;
    } & ParsedInitializeConfigInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.InitializeListing;
    } & ParsedInitializeListingInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.InitializeUserProfile;
    } & ParsedInitializeUserProfileInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.LinkIdentity;
    } & ParsedLinkIdentityInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.SetListingOccupied;
    } & ParsedSetListingOccupiedInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.UpdateDeposit;
    } & ParsedUpdateDepositInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.UpdateHostReview;
    } & ParsedUpdateHostReviewInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.UpdateListingPrice;
    } & ParsedUpdateListingPriceInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.UpdateListingPublish;
    } & ParsedUpdateListingPublishInstruction<TProgram>)
  | ({
      instructionType: StaykeCoreInstruction.UpdateListingState;
    } & ParsedUpdateListingStateInstruction<TProgram>);

export function parseStaykeCoreInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedStaykeCoreInstruction<TProgram> {
  const instructionType = identifyStaykeCoreInstruction(instruction);
  switch (instructionType) {
    case StaykeCoreInstruction.AddInfraction: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.AddInfraction,
        ...parseAddInfractionInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.ClearActiveBooking: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.ClearActiveBooking,
        ...parseClearActiveBookingInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.ClearListingBooking: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.ClearListingBooking,
        ...parseClearListingBookingInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.InitIdentity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.InitIdentity,
        ...parseInitIdentityInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.InitializeConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.InitializeConfig,
        ...parseInitializeConfigInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.InitializeListing: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.InitializeListing,
        ...parseInitializeListingInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.InitializeUserProfile: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.InitializeUserProfile,
        ...parseInitializeUserProfileInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.LinkIdentity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.LinkIdentity,
        ...parseLinkIdentityInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.SetListingOccupied: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.SetListingOccupied,
        ...parseSetListingOccupiedInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.UpdateDeposit: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.UpdateDeposit,
        ...parseUpdateDepositInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.UpdateHostReview: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.UpdateHostReview,
        ...parseUpdateHostReviewInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.UpdateListingPrice: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.UpdateListingPrice,
        ...parseUpdateListingPriceInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.UpdateListingPublish: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.UpdateListingPublish,
        ...parseUpdateListingPublishInstruction(instruction),
      };
    }
    case StaykeCoreInstruction.UpdateListingState: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StaykeCoreInstruction.UpdateListingState,
        ...parseUpdateListingStateInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        {
          instructionType: instructionType as string,
          programName: "staykeCore",
        },
      );
  }
}

export type StaykeCorePlugin = {
  accounts: StaykeCorePluginAccounts;
  instructions: StaykeCorePluginInstructions;
  pdas: StaykeCorePluginPdas;
};

export type StaykeCorePluginAccounts = {
  configAcc: ReturnType<typeof getConfigAccCodec> &
    SelfFetchFunctions<ConfigAccArgs, ConfigAcc>;
  identity: ReturnType<typeof getIdentityCodec> &
    SelfFetchFunctions<IdentityArgs, Identity>;
  listing: ReturnType<typeof getListingCodec> &
    SelfFetchFunctions<ListingArgs, Listing>;
  reputationProfile: ReturnType<typeof getReputationProfileCodec> &
    SelfFetchFunctions<ReputationProfileArgs, ReputationProfile>;
  userProfile: ReturnType<typeof getUserProfileCodec> &
    SelfFetchFunctions<UserProfileArgs, UserProfile>;
};

export type StaykeCorePluginInstructions = {
  addInfraction: (
    input: AddInfractionAsyncInput,
  ) => ReturnType<typeof getAddInfractionInstructionAsync> &
    SelfPlanAndSendFunctions;
  clearActiveBooking: (
    input: ClearActiveBookingAsyncInput,
  ) => ReturnType<typeof getClearActiveBookingInstructionAsync> &
    SelfPlanAndSendFunctions;
  clearListingBooking: (
    input: ClearListingBookingAsyncInput,
  ) => ReturnType<typeof getClearListingBookingInstructionAsync> &
    SelfPlanAndSendFunctions;
  initIdentity: (
    input: MakeOptional<InitIdentityAsyncInput, "payer">,
  ) => ReturnType<typeof getInitIdentityInstructionAsync> &
    SelfPlanAndSendFunctions;
  initializeConfig: (
    input: InitializeConfigAsyncInput,
  ) => ReturnType<typeof getInitializeConfigInstructionAsync> &
    SelfPlanAndSendFunctions;
  initializeListing: (
    input: MakeOptional<InitializeListingAsyncInput, "payer">,
  ) => ReturnType<typeof getInitializeListingInstructionAsync> &
    SelfPlanAndSendFunctions;
  initializeUserProfile: (
    input: MakeOptional<InitializeUserProfileAsyncInput, "payer">,
  ) => ReturnType<typeof getInitializeUserProfileInstructionAsync> &
    SelfPlanAndSendFunctions;
  linkIdentity: (
    input: MakeOptional<LinkIdentityAsyncInput, "payer">,
  ) => ReturnType<typeof getLinkIdentityInstructionAsync> &
    SelfPlanAndSendFunctions;
  setListingOccupied: (
    input: SetListingOccupiedAsyncInput,
  ) => ReturnType<typeof getSetListingOccupiedInstructionAsync> &
    SelfPlanAndSendFunctions;
  updateDeposit: (
    input: UpdateDepositAsyncInput,
  ) => ReturnType<typeof getUpdateDepositInstructionAsync> &
    SelfPlanAndSendFunctions;
  updateHostReview: (
    input: UpdateHostReviewAsyncInput,
  ) => ReturnType<typeof getUpdateHostReviewInstructionAsync> &
    SelfPlanAndSendFunctions;
  updateListingPrice: (
    input: MakeOptional<UpdateListingPriceAsyncInput, "payer">,
  ) => ReturnType<typeof getUpdateListingPriceInstructionAsync> &
    SelfPlanAndSendFunctions;
  updateListingPublish: (
    input: MakeOptional<UpdateListingPublishAsyncInput, "payer">,
  ) => ReturnType<typeof getUpdateListingPublishInstructionAsync> &
    SelfPlanAndSendFunctions;
  updateListingState: (
    input: MakeOptional<UpdateListingStateAsyncInput, "payer">,
  ) => ReturnType<typeof getUpdateListingStateInstructionAsync> &
    SelfPlanAndSendFunctions;
};

export type StaykeCorePluginPdas = {
  identity: typeof findIdentityPda;
  config: typeof findConfigPda;
  listing: typeof findListingPda;
  userProfile: typeof findUserProfilePda;
  reputationProfile: typeof findReputationProfilePda;
};

export type StaykeCorePluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
> &
  ClientWithPayer &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function staykeCoreProgram() {
  return <T extends StaykeCorePluginRequirements>(
    client: T,
  ): Omit<T, "staykeCore"> & { staykeCore: StaykeCorePlugin } => {
    return extendClient(client, {
      staykeCore: <StaykeCorePlugin>{
        accounts: {
          configAcc: addSelfFetchFunctions(client, getConfigAccCodec()),
          identity: addSelfFetchFunctions(client, getIdentityCodec()),
          listing: addSelfFetchFunctions(client, getListingCodec()),
          reputationProfile: addSelfFetchFunctions(
            client,
            getReputationProfileCodec(),
          ),
          userProfile: addSelfFetchFunctions(client, getUserProfileCodec()),
        },
        instructions: {
          addInfraction: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAddInfractionInstructionAsync(input),
            ),
          clearActiveBooking: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getClearActiveBookingInstructionAsync(input),
            ),
          clearListingBooking: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getClearListingBookingInstructionAsync(input),
            ),
          initIdentity: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitIdentityInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          initializeConfig: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeConfigInstructionAsync(input),
            ),
          initializeListing: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeListingInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          initializeUserProfile: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeUserProfileInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          linkIdentity: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getLinkIdentityInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          setListingOccupied: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetListingOccupiedInstructionAsync(input),
            ),
          updateDeposit: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateDepositInstructionAsync(input),
            ),
          updateHostReview: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateHostReviewInstructionAsync(input),
            ),
          updateListingPrice: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateListingPriceInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          updateListingPublish: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateListingPublishInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          updateListingState: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateListingStateInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
        },
        pdas: {
          identity: findIdentityPda,
          config: findConfigPda,
          listing: findListingPda,
          userProfile: findUserProfilePda,
          reputationProfile: findReputationProfilePda,
        },
      },
    });
  };
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
