[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
stayke_config = "29A2HXuDHX8WQoPnYbFP4DR4W6HjQTBDA2N5pCPZEFs4"
stayke_core = "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm"
stayke_treasury = "3JE5y7vtjkZkA6s3eRAKorT1eQmgoJQmnVqpy15uUjq8"
stayke_escrow = "68ipZiXiUhsaSYSqEM3619vXgKy5CqFmNE6rYzxrXu6a"
stayke_disputes = "89yo4qWuvaQcAPtAcutNB6vht3JwvEwMMLbSwpMM2Czt"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/RRPxZ9enn2QeJ47Hzs89nngHgfXTYGC0"
wallet = "./keypair.json"

[scripts]
test = "cargo test"

[hooks]
