/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findCpiAuthorityPda } from "../pdas";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const BOOKING_STARTS_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  95, 49, 174, 33, 85, 74, 101, 56,
]);

export function getBookingStartsDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    BOOKING_STARTS_DISCRIMINATOR,
  );
}

export type BookingStartsInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountGuest extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountStaykeCore extends string | AccountMeta<string> =
    "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountGuest extends string
        ? WritableAccount<TAccountGuest>
        : TAccountGuest,
      TAccountCpiAuthority extends string
        ? ReadonlyAccount<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountStaykeCore extends string
        ? ReadonlyAccount<TAccountStaykeCore>
        : TAccountStaykeCore,
      ...TRemainingAccounts,
    ]
  >;

export type BookingStartsInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type BookingStartsInstructionDataArgs = {};

export function getBookingStartsInstructionDataEncoder(): FixedSizeEncoder<BookingStartsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: BOOKING_STARTS_DISCRIMINATOR }),
  );
}

export function getBookingStartsInstructionDataDecoder(): FixedSizeDecoder<BookingStartsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getBookingStartsInstructionDataCodec(): FixedSizeCodec<
  BookingStartsInstructionDataArgs,
  BookingStartsInstructionData
> {
  return combineCodec(
    getBookingStartsInstructionDataEncoder(),
    getBookingStartsInstructionDataDecoder(),
  );
}

export type BookingStartsAsyncInput<
  TAccountPayer extends string = string,
  TAccountBooking extends string = string,
  TAccountGuest extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountStaykeCore extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  booking: Address<TAccountBooking>;
  guest: Address<TAccountGuest>;
  cpiAuthority?: Address<TAccountCpiAuthority>;
  globalConfig?: Address<TAccountGlobalConfig>;
  staykeCore?: Address<TAccountStaykeCore>;
};

export async function getBookingStartsInstructionAsync<
  TAccountPayer extends string,
  TAccountBooking extends string,
  TAccountGuest extends string,
  TAccountCpiAuthority extends string,
  TAccountGlobalConfig extends string,
  TAccountStaykeCore extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: BookingStartsAsyncInput<
    TAccountPayer,
    TAccountBooking,
    TAccountGuest,
    TAccountCpiAuthority,
    TAccountGlobalConfig,
    TAccountStaykeCore
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  BookingStartsInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountBooking,
    TAccountGuest,
    TAccountCpiAuthority,
    TAccountGlobalConfig,
    TAccountStaykeCore
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    guest: { value: input.guest ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    staykeCore: { value: input.staykeCore ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.cpiAuthority.value) {
    accounts.cpiAuthority.value = await findCpiAuthorityPda();
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.staykeCore.value) {
    accounts.staykeCore.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("guest", accounts.guest),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("staykeCore", accounts.staykeCore),
    ],
    data: getBookingStartsInstructionDataEncoder().encode({}),
    programAddress,
  } as BookingStartsInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountBooking,
    TAccountGuest,
    TAccountCpiAuthority,
    TAccountGlobalConfig,
    TAccountStaykeCore
  >);
}

export type BookingStartsInput<
  TAccountPayer extends string = string,
  TAccountBooking extends string = string,
  TAccountGuest extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountStaykeCore extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  booking: Address<TAccountBooking>;
  guest: Address<TAccountGuest>;
  cpiAuthority: Address<TAccountCpiAuthority>;
  globalConfig: Address<TAccountGlobalConfig>;
  staykeCore?: Address<TAccountStaykeCore>;
};

export function getBookingStartsInstruction<
  TAccountPayer extends string,
  TAccountBooking extends string,
  TAccountGuest extends string,
  TAccountCpiAuthority extends string,
  TAccountGlobalConfig extends string,
  TAccountStaykeCore extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: BookingStartsInput<
    TAccountPayer,
    TAccountBooking,
    TAccountGuest,
    TAccountCpiAuthority,
    TAccountGlobalConfig,
    TAccountStaykeCore
  >,
  config?: { programAddress?: TProgramAddress },
): BookingStartsInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountBooking,
  TAccountGuest,
  TAccountCpiAuthority,
  TAccountGlobalConfig,
  TAccountStaykeCore
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    guest: { value: input.guest ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    staykeCore: { value: input.staykeCore ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.staykeCore.value) {
    accounts.staykeCore.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("guest", accounts.guest),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("staykeCore", accounts.staykeCore),
    ],
    data: getBookingStartsInstructionDataEncoder().encode({}),
    programAddress,
  } as BookingStartsInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountBooking,
    TAccountGuest,
    TAccountCpiAuthority,
    TAccountGlobalConfig,
    TAccountStaykeCore
  >);
}

export type ParsedBookingStartsInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    booking: TAccountMetas[1];
    guest: TAccountMetas[2];
    cpiAuthority: TAccountMetas[3];
    globalConfig: TAccountMetas[4];
    staykeCore: TAccountMetas[5];
  };
  data: BookingStartsInstructionData;
};

export function parseBookingStartsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedBookingStartsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      booking: getNextAccount(),
      guest: getNextAccount(),
      cpiAuthority: getNextAccount(),
      globalConfig: getNextAccount(),
      staykeCore: getNextAccount(),
    },
    data: getBookingStartsInstructionDataDecoder().decode(instruction.data),
  };
}
