/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findCpiAuthorityPda,
  findEscrowConfigPda,
  findEscrowTokenAccountPda,
} from "../pdas";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const COMPLETE_STAY_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  112, 64, 94, 245, 123, 205, 57, 182,
]);

export function getCompleteStayDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    COMPLETE_STAY_DISCRIMINATOR,
  );
}

export type CompleteStayInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountClient extends string | AccountMeta<string> = string,
  TAccountClientProfile extends string | AccountMeta<string> = string,
  TAccountHostProfile extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountEscrowConfig extends string | AccountMeta<string> = string,
  TAccountEscrowTokenAccount extends string | AccountMeta<string> = string,
  TAccountHostTokenAccount extends string | AccountMeta<string> = string,
  TAccountPlatformVault extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TAccountStaykeCoreProgram extends string | AccountMeta<string> =
    "8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountClient extends string
        ? ReadonlySignerAccount<TAccountClient> &
            AccountSignerMeta<TAccountClient>
        : TAccountClient,
      TAccountClientProfile extends string
        ? WritableAccount<TAccountClientProfile>
        : TAccountClientProfile,
      TAccountHostProfile extends string
        ? ReadonlyAccount<TAccountHostProfile>
        : TAccountHostProfile,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountEscrowConfig extends string
        ? ReadonlyAccount<TAccountEscrowConfig>
        : TAccountEscrowConfig,
      TAccountEscrowTokenAccount extends string
        ? WritableAccount<TAccountEscrowTokenAccount>
        : TAccountEscrowTokenAccount,
      TAccountHostTokenAccount extends string
        ? WritableAccount<TAccountHostTokenAccount>
        : TAccountHostTokenAccount,
      TAccountPlatformVault extends string
        ? WritableAccount<TAccountPlatformVault>
        : TAccountPlatformVault,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountCpiAuthority extends string
        ? ReadonlyAccount<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      TAccountStaykeCoreProgram extends string
        ? ReadonlyAccount<TAccountStaykeCoreProgram>
        : TAccountStaykeCoreProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CompleteStayInstructionData = { discriminator: ReadonlyUint8Array };

export type CompleteStayInstructionDataArgs = {};

export function getCompleteStayInstructionDataEncoder(): FixedSizeEncoder<CompleteStayInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: COMPLETE_STAY_DISCRIMINATOR }),
  );
}

export function getCompleteStayInstructionDataDecoder(): FixedSizeDecoder<CompleteStayInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCompleteStayInstructionDataCodec(): FixedSizeCodec<
  CompleteStayInstructionDataArgs,
  CompleteStayInstructionData
> {
  return combineCodec(
    getCompleteStayInstructionDataEncoder(),
    getCompleteStayInstructionDataDecoder(),
  );
}

export type CompleteStayAsyncInput<
  TAccountPayer extends string = string,
  TAccountClient extends string = string,
  TAccountClientProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountBooking extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowConfig extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountHostTokenAccount extends string = string,
  TAccountPlatformVault extends string = string,
  TAccountMint extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  client: TransactionSigner<TAccountClient>;
  /** The guest's UserProfile — must be mutable for CPI to increment completed_stays. */
  clientProfile?: Address<TAccountClientProfile>;
  /** The host's UserProfile — destination for the payment. */
  hostProfile: Address<TAccountHostProfile>;
  booking: Address<TAccountBooking>;
  globalConfig?: Address<TAccountGlobalConfig>;
  escrowConfig?: Address<TAccountEscrowConfig>;
  escrowTokenAccount?: Address<TAccountEscrowTokenAccount>;
  /** The host's USDC token account. */
  hostTokenAccount: Address<TAccountHostTokenAccount>;
  /** Platform fee vault. */
  platformVault: Address<TAccountPlatformVault>;
  mint: Address<TAccountMint>;
  cpiAuthority?: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getCompleteStayInstructionAsync<
  TAccountPayer extends string,
  TAccountClient extends string,
  TAccountClientProfile extends string,
  TAccountHostProfile extends string,
  TAccountBooking extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowConfig extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountHostTokenAccount extends string,
  TAccountPlatformVault extends string,
  TAccountMint extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: CompleteStayAsyncInput<
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CompleteStayInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    client: { value: input.client ?? null, isWritable: false },
    clientProfile: { value: input.clientProfile ?? null, isWritable: true },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowConfig: { value: input.escrowConfig ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    hostTokenAccount: {
      value: input.hostTokenAccount ?? null,
      isWritable: true,
    },
    platformVault: { value: input.platformVault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.clientProfile.value) {
    accounts.clientProfile.value = await getProgramDerivedAddress({
      programAddress:
        "8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP" as Address<"8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            117, 115, 101, 114, 95, 112, 114, 111, 102, 105, 108, 101,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "client",
            accounts.client.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW" as Address<"2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.escrowConfig.value) {
    accounts.escrowConfig.value = await findEscrowConfigPda();
  }
  if (!accounts.escrowTokenAccount.value) {
    accounts.escrowTokenAccount.value = await findEscrowTokenAccountPda({
      booking: getAddressFromResolvedInstructionAccount(
        "booking",
        accounts.booking.value,
      ),
    });
  }
  if (!accounts.cpiAuthority.value) {
    accounts.cpiAuthority.value = await findCpiAuthorityPda();
  }
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP" as Address<"8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("client", accounts.client),
      getAccountMeta("clientProfile", accounts.clientProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowConfig", accounts.escrowConfig),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("hostTokenAccount", accounts.hostTokenAccount),
      getAccountMeta("platformVault", accounts.platformVault),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getCompleteStayInstructionDataEncoder().encode({}),
    programAddress,
  } as CompleteStayInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >);
}

export type CompleteStayInput<
  TAccountPayer extends string = string,
  TAccountClient extends string = string,
  TAccountClientProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountBooking extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowConfig extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountHostTokenAccount extends string = string,
  TAccountPlatformVault extends string = string,
  TAccountMint extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  client: TransactionSigner<TAccountClient>;
  /** The guest's UserProfile — must be mutable for CPI to increment completed_stays. */
  clientProfile: Address<TAccountClientProfile>;
  /** The host's UserProfile — destination for the payment. */
  hostProfile: Address<TAccountHostProfile>;
  booking: Address<TAccountBooking>;
  globalConfig: Address<TAccountGlobalConfig>;
  escrowConfig: Address<TAccountEscrowConfig>;
  escrowTokenAccount: Address<TAccountEscrowTokenAccount>;
  /** The host's USDC token account. */
  hostTokenAccount: Address<TAccountHostTokenAccount>;
  /** Platform fee vault. */
  platformVault: Address<TAccountPlatformVault>;
  mint: Address<TAccountMint>;
  cpiAuthority: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getCompleteStayInstruction<
  TAccountPayer extends string,
  TAccountClient extends string,
  TAccountClientProfile extends string,
  TAccountHostProfile extends string,
  TAccountBooking extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowConfig extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountHostTokenAccount extends string,
  TAccountPlatformVault extends string,
  TAccountMint extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: CompleteStayInput<
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CompleteStayInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountClient,
  TAccountClientProfile,
  TAccountHostProfile,
  TAccountBooking,
  TAccountGlobalConfig,
  TAccountEscrowConfig,
  TAccountEscrowTokenAccount,
  TAccountHostTokenAccount,
  TAccountPlatformVault,
  TAccountMint,
  TAccountCpiAuthority,
  TAccountStaykeCoreProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    client: { value: input.client ?? null, isWritable: false },
    clientProfile: { value: input.clientProfile ?? null, isWritable: true },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowConfig: { value: input.escrowConfig ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    hostTokenAccount: {
      value: input.hostTokenAccount ?? null,
      isWritable: true,
    },
    platformVault: { value: input.platformVault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP" as Address<"8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("client", accounts.client),
      getAccountMeta("clientProfile", accounts.clientProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowConfig", accounts.escrowConfig),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("hostTokenAccount", accounts.hostTokenAccount),
      getAccountMeta("platformVault", accounts.platformVault),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getCompleteStayInstructionDataEncoder().encode({}),
    programAddress,
  } as CompleteStayInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig,
    TAccountEscrowTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >);
}

export type ParsedCompleteStayInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    client: TAccountMetas[1];
    /** The guest's UserProfile — must be mutable for CPI to increment completed_stays. */
    clientProfile: TAccountMetas[2];
    /** The host's UserProfile — destination for the payment. */
    hostProfile: TAccountMetas[3];
    booking: TAccountMetas[4];
    globalConfig: TAccountMetas[5];
    escrowConfig: TAccountMetas[6];
    escrowTokenAccount: TAccountMetas[7];
    /** The host's USDC token account. */
    hostTokenAccount: TAccountMetas[8];
    /** Platform fee vault. */
    platformVault: TAccountMetas[9];
    mint: TAccountMetas[10];
    cpiAuthority: TAccountMetas[11];
    staykeCoreProgram: TAccountMetas[12];
    tokenProgram: TAccountMetas[13];
  };
  data: CompleteStayInstructionData;
};

export function parseCompleteStayInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCompleteStayInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 14) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 14,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      client: getNextAccount(),
      clientProfile: getNextAccount(),
      hostProfile: getNextAccount(),
      booking: getNextAccount(),
      globalConfig: getNextAccount(),
      escrowConfig: getNextAccount(),
      escrowTokenAccount: getNextAccount(),
      hostTokenAccount: getNextAccount(),
      platformVault: getNextAccount(),
      mint: getNextAccount(),
      cpiAuthority: getNextAccount(),
      staykeCoreProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getCompleteStayInstructionDataDecoder().decode(instruction.data),
  };
}
