/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";
import {
  getBookingStatusDecoder,
  getBookingStatusEncoder,
  type BookingStatus,
  type BookingStatusArgs,
} from "../types";

export const CPI_UPDATE_BOOKING_STATUS_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([225, 169, 181, 166, 175, 12, 138, 50]);

export function getCpiUpdateBookingStatusDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CPI_UPDATE_BOOKING_STATUS_DISCRIMINATOR,
  );
}

export type CpiUpdateBookingStatusInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountCpiAuthority extends string
        ? ReadonlySignerAccount<TAccountCpiAuthority> &
            AccountSignerMeta<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type CpiUpdateBookingStatusInstructionData = {
  discriminator: ReadonlyUint8Array;
  status: BookingStatus;
};

export type CpiUpdateBookingStatusInstructionDataArgs = {
  status: BookingStatusArgs;
};

export function getCpiUpdateBookingStatusInstructionDataEncoder(): FixedSizeEncoder<CpiUpdateBookingStatusInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["status", getBookingStatusEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: CPI_UPDATE_BOOKING_STATUS_DISCRIMINATOR,
    }),
  );
}

export function getCpiUpdateBookingStatusInstructionDataDecoder(): FixedSizeDecoder<CpiUpdateBookingStatusInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["status", getBookingStatusDecoder()],
  ]);
}

export function getCpiUpdateBookingStatusInstructionDataCodec(): FixedSizeCodec<
  CpiUpdateBookingStatusInstructionDataArgs,
  CpiUpdateBookingStatusInstructionData
> {
  return combineCodec(
    getCpiUpdateBookingStatusInstructionDataEncoder(),
    getCpiUpdateBookingStatusInstructionDataDecoder(),
  );
}

export type CpiUpdateBookingStatusAsyncInput<
  TAccountGlobalConfig extends string = string,
  TAccountBooking extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  globalConfig?: Address<TAccountGlobalConfig>;
  booking: Address<TAccountBooking>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  status: CpiUpdateBookingStatusInstructionDataArgs["status"];
};

export async function getCpiUpdateBookingStatusInstructionAsync<
  TAccountGlobalConfig extends string,
  TAccountBooking extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: CpiUpdateBookingStatusAsyncInput<
    TAccountGlobalConfig,
    TAccountBooking,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CpiUpdateBookingStatusInstruction<
    TProgramAddress,
    TAccountGlobalConfig,
    TAccountBooking,
    TAccountCpiAuthority
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW" as Address<"2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getCpiUpdateBookingStatusInstructionDataEncoder().encode(
      args as CpiUpdateBookingStatusInstructionDataArgs,
    ),
    programAddress,
  } as CpiUpdateBookingStatusInstruction<
    TProgramAddress,
    TAccountGlobalConfig,
    TAccountBooking,
    TAccountCpiAuthority
  >);
}

export type CpiUpdateBookingStatusInput<
  TAccountGlobalConfig extends string = string,
  TAccountBooking extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  globalConfig: Address<TAccountGlobalConfig>;
  booking: Address<TAccountBooking>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  status: CpiUpdateBookingStatusInstructionDataArgs["status"];
};

export function getCpiUpdateBookingStatusInstruction<
  TAccountGlobalConfig extends string,
  TAccountBooking extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: CpiUpdateBookingStatusInput<
    TAccountGlobalConfig,
    TAccountBooking,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): CpiUpdateBookingStatusInstruction<
  TProgramAddress,
  TAccountGlobalConfig,
  TAccountBooking,
  TAccountCpiAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getCpiUpdateBookingStatusInstructionDataEncoder().encode(
      args as CpiUpdateBookingStatusInstructionDataArgs,
    ),
    programAddress,
  } as CpiUpdateBookingStatusInstruction<
    TProgramAddress,
    TAccountGlobalConfig,
    TAccountBooking,
    TAccountCpiAuthority
  >);
}

export type ParsedCpiUpdateBookingStatusInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    globalConfig: TAccountMetas[0];
    booking: TAccountMetas[1];
    cpiAuthority: TAccountMetas[2];
  };
  data: CpiUpdateBookingStatusInstructionData;
};

export function parseCpiUpdateBookingStatusInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCpiUpdateBookingStatusInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      globalConfig: getNextAccount(),
      booking: getNextAccount(),
      cpiAuthority: getNextAccount(),
    },
    data: getCpiUpdateBookingStatusInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
