/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  getNonNullResolvedInstructionInput,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findBookingDaysPda, findBookingPda } from "../pdas";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const CREATE_BOOKING_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  19, 223, 181, 90, 124, 206, 73, 169,
]);

export function getCreateBookingDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_BOOKING_DISCRIMINATOR,
  );
}

export type CreateBookingInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountClient extends string | AccountMeta<string> = string,
  TAccountClientProfile extends string | AccountMeta<string> = string,
  TAccountHostProfile extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountProperty extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountBookingDays extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountClient extends string
        ? ReadonlySignerAccount<TAccountClient> &
            AccountSignerMeta<TAccountClient>
        : TAccountClient,
      TAccountClientProfile extends string
        ? ReadonlyAccount<TAccountClientProfile>
        : TAccountClientProfile,
      TAccountHostProfile extends string
        ? ReadonlyAccount<TAccountHostProfile>
        : TAccountHostProfile,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountProperty extends string
        ? ReadonlyAccount<TAccountProperty>
        : TAccountProperty,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountBookingDays extends string
        ? WritableAccount<TAccountBookingDays>
        : TAccountBookingDays,
      ...TRemainingAccounts,
    ]
  >;

export type CreateBookingInstructionData = {
  discriminator: ReadonlyUint8Array;
  checkIn: bigint;
  checkOut: bigint;
};

export type CreateBookingInstructionDataArgs = {
  checkIn: number | bigint;
  checkOut: number | bigint;
};

export function getCreateBookingInstructionDataEncoder(): FixedSizeEncoder<CreateBookingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["checkIn", getI64Encoder()],
      ["checkOut", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_BOOKING_DISCRIMINATOR }),
  );
}

export function getCreateBookingInstructionDataDecoder(): FixedSizeDecoder<CreateBookingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["checkIn", getI64Decoder()],
    ["checkOut", getI64Decoder()],
  ]);
}

export function getCreateBookingInstructionDataCodec(): FixedSizeCodec<
  CreateBookingInstructionDataArgs,
  CreateBookingInstructionData
> {
  return combineCodec(
    getCreateBookingInstructionDataEncoder(),
    getCreateBookingInstructionDataDecoder(),
  );
}

export type CreateBookingAsyncInput<
  TAccountPayer extends string = string,
  TAccountClient extends string = string,
  TAccountClientProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountBooking extends string = string,
  TAccountProperty extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountBookingDays extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  client: TransactionSigner<TAccountClient>;
  /** The guest's UserProfile from stayke-core. */
  clientProfile?: Address<TAccountClientProfile>;
  /** The host's UserProfile from stayke-core. */
  hostProfile: Address<TAccountHostProfile>;
  booking?: Address<TAccountBooking>;
  property: Address<TAccountProperty>;
  globalConfig?: Address<TAccountGlobalConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  bookingDays?: Address<TAccountBookingDays>;
  checkIn: CreateBookingInstructionDataArgs["checkIn"];
  checkOut: CreateBookingInstructionDataArgs["checkOut"];
};

export async function getCreateBookingInstructionAsync<
  TAccountPayer extends string,
  TAccountClient extends string,
  TAccountClientProfile extends string,
  TAccountHostProfile extends string,
  TAccountBooking extends string,
  TAccountProperty extends string,
  TAccountGlobalConfig extends string,
  TAccountSystemProgram extends string,
  TAccountBookingDays extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: CreateBookingAsyncInput<
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountProperty,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountBookingDays
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CreateBookingInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountProperty,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountBookingDays
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    client: { value: input.client ?? null, isWritable: false },
    clientProfile: { value: input.clientProfile ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    property: { value: input.property ?? null, isWritable: false },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.clientProfile.value) {
    accounts.clientProfile.value = await getProgramDerivedAddress({
      programAddress:
        "8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP" as Address<"8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            117, 115, 101, 114, 95, 112, 114, 111, 102, 105, 108, 101,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "client",
            accounts.client.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.booking.value) {
    accounts.booking.value = await findBookingPda({
      property: getAddressFromResolvedInstructionAccount(
        "property",
        accounts.property.value,
      ),
      clientProfile: getAddressFromResolvedInstructionAccount(
        "clientProfile",
        accounts.clientProfile.value,
      ),
      checkIn: getNonNullResolvedInstructionInput("checkIn", args.checkIn),
    });
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW" as Address<"2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.bookingDays.value) {
    accounts.bookingDays.value = await findBookingDaysPda({
      property: getAddressFromResolvedInstructionAccount(
        "property",
        accounts.property.value,
      ),
      checkIn: getNonNullResolvedInstructionInput("checkIn", args.checkIn),
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("client", accounts.client),
      getAccountMeta("clientProfile", accounts.clientProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("property", accounts.property),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("bookingDays", accounts.bookingDays),
    ],
    data: getCreateBookingInstructionDataEncoder().encode(
      args as CreateBookingInstructionDataArgs,
    ),
    programAddress,
  } as CreateBookingInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountProperty,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountBookingDays
  >);
}

export type CreateBookingInput<
  TAccountPayer extends string = string,
  TAccountClient extends string = string,
  TAccountClientProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountBooking extends string = string,
  TAccountProperty extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountBookingDays extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  client: TransactionSigner<TAccountClient>;
  /** The guest's UserProfile from stayke-core. */
  clientProfile: Address<TAccountClientProfile>;
  /** The host's UserProfile from stayke-core. */
  hostProfile: Address<TAccountHostProfile>;
  booking: Address<TAccountBooking>;
  property: Address<TAccountProperty>;
  globalConfig: Address<TAccountGlobalConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  bookingDays: Address<TAccountBookingDays>;
  checkIn: CreateBookingInstructionDataArgs["checkIn"];
  checkOut: CreateBookingInstructionDataArgs["checkOut"];
};

export function getCreateBookingInstruction<
  TAccountPayer extends string,
  TAccountClient extends string,
  TAccountClientProfile extends string,
  TAccountHostProfile extends string,
  TAccountBooking extends string,
  TAccountProperty extends string,
  TAccountGlobalConfig extends string,
  TAccountSystemProgram extends string,
  TAccountBookingDays extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: CreateBookingInput<
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountProperty,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountBookingDays
  >,
  config?: { programAddress?: TProgramAddress },
): CreateBookingInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountClient,
  TAccountClientProfile,
  TAccountHostProfile,
  TAccountBooking,
  TAccountProperty,
  TAccountGlobalConfig,
  TAccountSystemProgram,
  TAccountBookingDays
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    client: { value: input.client ?? null, isWritable: false },
    clientProfile: { value: input.clientProfile ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    property: { value: input.property ?? null, isWritable: false },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("client", accounts.client),
      getAccountMeta("clientProfile", accounts.clientProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("property", accounts.property),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("bookingDays", accounts.bookingDays),
    ],
    data: getCreateBookingInstructionDataEncoder().encode(
      args as CreateBookingInstructionDataArgs,
    ),
    programAddress,
  } as CreateBookingInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountBooking,
    TAccountProperty,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountBookingDays
  >);
}

export type ParsedCreateBookingInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    client: TAccountMetas[1];
    /** The guest's UserProfile from stayke-core. */
    clientProfile: TAccountMetas[2];
    /** The host's UserProfile from stayke-core. */
    hostProfile: TAccountMetas[3];
    booking: TAccountMetas[4];
    property: TAccountMetas[5];
    globalConfig: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
    bookingDays: TAccountMetas[8];
  };
  data: CreateBookingInstructionData;
};

export function parseCreateBookingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateBookingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      client: getNextAccount(),
      clientProfile: getNextAccount(),
      hostProfile: getNextAccount(),
      booking: getNextAccount(),
      property: getNextAccount(),
      globalConfig: getNextAccount(),
      systemProgram: getNextAccount(),
      bookingDays: getNextAccount(),
    },
    data: getCreateBookingInstructionDataDecoder().decode(instruction.data),
  };
}
