/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findEscrowTokenAccountPda } from "../pdas";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const EXPIRE_BOOKING_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  195, 5, 103, 244, 83, 155, 236, 125,
]);

export function getExpireBookingDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    EXPIRE_BOOKING_DISCRIMINATOR,
  );
}

export type ExpireBookingInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountGuest extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountEscrowTokenAccount extends string | AccountMeta<string> = string,
  TAccountGuestTokenAccount extends string | AccountMeta<string> = string,
  TAccountBookingDays extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountGuest extends string
        ? ReadonlyAccount<TAccountGuest>
        : TAccountGuest,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountEscrowTokenAccount extends string
        ? WritableAccount<TAccountEscrowTokenAccount>
        : TAccountEscrowTokenAccount,
      TAccountGuestTokenAccount extends string
        ? WritableAccount<TAccountGuestTokenAccount>
        : TAccountGuestTokenAccount,
      TAccountBookingDays extends string
        ? WritableAccount<TAccountBookingDays>
        : TAccountBookingDays,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ExpireBookingInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ExpireBookingInstructionDataArgs = {};

export function getExpireBookingInstructionDataEncoder(): FixedSizeEncoder<ExpireBookingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: EXPIRE_BOOKING_DISCRIMINATOR }),
  );
}

export function getExpireBookingInstructionDataDecoder(): FixedSizeDecoder<ExpireBookingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getExpireBookingInstructionDataCodec(): FixedSizeCodec<
  ExpireBookingInstructionDataArgs,
  ExpireBookingInstructionData
> {
  return combineCodec(
    getExpireBookingInstructionDataEncoder(),
    getExpireBookingInstructionDataDecoder(),
  );
}

export type ExpireBookingAsyncInput<
  TAccountPayer extends string = string,
  TAccountGuest extends string = string,
  TAccountBooking extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountBookingDays extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountMint extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  guest: Address<TAccountGuest>;
  booking: Address<TAccountBooking>;
  escrowTokenAccount?: Address<TAccountEscrowTokenAccount>;
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  bookingDays: Address<TAccountBookingDays>;
  globalConfig?: Address<TAccountGlobalConfig>;
  mint: Address<TAccountMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getExpireBookingInstructionAsync<
  TAccountPayer extends string,
  TAccountGuest extends string,
  TAccountBooking extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountBookingDays extends string,
  TAccountGlobalConfig extends string,
  TAccountMint extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: ExpireBookingAsyncInput<
    TAccountPayer,
    TAccountGuest,
    TAccountBooking,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ExpireBookingInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountGuest,
    TAccountBooking,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountMint,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    guest: { value: input.guest ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.escrowTokenAccount.value) {
    accounts.escrowTokenAccount.value = await findEscrowTokenAccountPda({
      booking: getAddressFromResolvedInstructionAccount(
        "booking",
        accounts.booking.value,
      ),
    });
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("guest", accounts.guest),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getExpireBookingInstructionDataEncoder().encode({}),
    programAddress,
  } as ExpireBookingInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountGuest,
    TAccountBooking,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountMint,
    TAccountTokenProgram
  >);
}

export type ExpireBookingInput<
  TAccountPayer extends string = string,
  TAccountGuest extends string = string,
  TAccountBooking extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountBookingDays extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountMint extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  guest: Address<TAccountGuest>;
  booking: Address<TAccountBooking>;
  escrowTokenAccount: Address<TAccountEscrowTokenAccount>;
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  bookingDays: Address<TAccountBookingDays>;
  globalConfig: Address<TAccountGlobalConfig>;
  mint: Address<TAccountMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getExpireBookingInstruction<
  TAccountPayer extends string,
  TAccountGuest extends string,
  TAccountBooking extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountBookingDays extends string,
  TAccountGlobalConfig extends string,
  TAccountMint extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: ExpireBookingInput<
    TAccountPayer,
    TAccountGuest,
    TAccountBooking,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ExpireBookingInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountGuest,
  TAccountBooking,
  TAccountEscrowTokenAccount,
  TAccountGuestTokenAccount,
  TAccountBookingDays,
  TAccountGlobalConfig,
  TAccountMint,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    guest: { value: input.guest ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("guest", accounts.guest),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getExpireBookingInstructionDataEncoder().encode({}),
    programAddress,
  } as ExpireBookingInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountGuest,
    TAccountBooking,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountMint,
    TAccountTokenProgram
  >);
}

export type ParsedExpireBookingInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    guest: TAccountMetas[1];
    booking: TAccountMetas[2];
    escrowTokenAccount: TAccountMetas[3];
    guestTokenAccount: TAccountMetas[4];
    bookingDays: TAccountMetas[5];
    globalConfig: TAccountMetas[6];
    mint: TAccountMetas[7];
    tokenProgram: TAccountMetas[8];
  };
  data: ExpireBookingInstructionData;
};

export function parseExpireBookingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedExpireBookingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      guest: getNextAccount(),
      booking: getNextAccount(),
      escrowTokenAccount: getNextAccount(),
      guestTokenAccount: getNextAccount(),
      bookingDays: getNextAccount(),
      globalConfig: getNextAccount(),
      mint: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getExpireBookingInstructionDataDecoder().decode(instruction.data),
  };
}
