/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findCpiAuthorityPda, findEscrowTokenAccountPda } from "../pdas";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const GUEST_CANCEL_BOOKING_CROSS_YEAR_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([235, 96, 56, 80, 77, 188, 210, 240]);

export function getGuestCancelBookingCrossYearDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    GUEST_CANCEL_BOOKING_CROSS_YEAR_DISCRIMINATOR,
  );
}

export type GuestCancelBookingCrossYearInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountGuestProfile extends string | AccountMeta<string> = string,
  TAccountHostProfile extends string | AccountMeta<string> = string,
  TAccountGuestReputation extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountBookingDays extends string | AccountMeta<string> = string,
  TAccountBookingDaysNext extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountEscrowTokenAccount extends string | AccountMeta<string> = string,
  TAccountGuestTokenAccount extends string | AccountMeta<string> = string,
  TAccountHostTokenAccount extends string | AccountMeta<string> = string,
  TAccountPlatformVault extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TAccountStaykeCoreProgram extends string | AccountMeta<string> =
    "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? WritableSignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountGuestProfile extends string
        ? ReadonlyAccount<TAccountGuestProfile>
        : TAccountGuestProfile,
      TAccountHostProfile extends string
        ? ReadonlyAccount<TAccountHostProfile>
        : TAccountHostProfile,
      TAccountGuestReputation extends string
        ? WritableAccount<TAccountGuestReputation>
        : TAccountGuestReputation,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountBookingDays extends string
        ? WritableAccount<TAccountBookingDays>
        : TAccountBookingDays,
      TAccountBookingDaysNext extends string
        ? WritableAccount<TAccountBookingDaysNext>
        : TAccountBookingDaysNext,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountEscrowTokenAccount extends string
        ? WritableAccount<TAccountEscrowTokenAccount>
        : TAccountEscrowTokenAccount,
      TAccountGuestTokenAccount extends string
        ? WritableAccount<TAccountGuestTokenAccount>
        : TAccountGuestTokenAccount,
      TAccountHostTokenAccount extends string
        ? WritableAccount<TAccountHostTokenAccount>
        : TAccountHostTokenAccount,
      TAccountPlatformVault extends string
        ? WritableAccount<TAccountPlatformVault>
        : TAccountPlatformVault,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountCpiAuthority extends string
        ? ReadonlyAccount<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      TAccountStaykeCoreProgram extends string
        ? ReadonlyAccount<TAccountStaykeCoreProgram>
        : TAccountStaykeCoreProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type GuestCancelBookingCrossYearInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type GuestCancelBookingCrossYearInstructionDataArgs = {};

export function getGuestCancelBookingCrossYearInstructionDataEncoder(): FixedSizeEncoder<GuestCancelBookingCrossYearInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: GUEST_CANCEL_BOOKING_CROSS_YEAR_DISCRIMINATOR,
    }),
  );
}

export function getGuestCancelBookingCrossYearInstructionDataDecoder(): FixedSizeDecoder<GuestCancelBookingCrossYearInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getGuestCancelBookingCrossYearInstructionDataCodec(): FixedSizeCodec<
  GuestCancelBookingCrossYearInstructionDataArgs,
  GuestCancelBookingCrossYearInstructionData
> {
  return combineCodec(
    getGuestCancelBookingCrossYearInstructionDataEncoder(),
    getGuestCancelBookingCrossYearInstructionDataDecoder(),
  );
}

export type GuestCancelBookingCrossYearAsyncInput<
  TAccountCaller extends string = string,
  TAccountGuestProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountGuestReputation extends string = string,
  TAccountBooking extends string = string,
  TAccountBookingDays extends string = string,
  TAccountBookingDaysNext extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountHostTokenAccount extends string = string,
  TAccountPlatformVault extends string = string,
  TAccountMint extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  caller: TransactionSigner<TAccountCaller>;
  guestProfile: Address<TAccountGuestProfile>;
  hostProfile: Address<TAccountHostProfile>;
  guestReputation: Address<TAccountGuestReputation>;
  booking: Address<TAccountBooking>;
  /** In the future, property will store config data for slashing guest cancelation */
  bookingDays: Address<TAccountBookingDays>;
  /** Availability bitmap for the following year — released on cancellation. */
  bookingDaysNext: Address<TAccountBookingDaysNext>;
  globalConfig?: Address<TAccountGlobalConfig>;
  escrowTokenAccount?: Address<TAccountEscrowTokenAccount>;
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  hostTokenAccount: Address<TAccountHostTokenAccount>;
  platformVault: Address<TAccountPlatformVault>;
  mint: Address<TAccountMint>;
  /** stayke-core. */
  cpiAuthority?: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getGuestCancelBookingCrossYearInstructionAsync<
  TAccountCaller extends string,
  TAccountGuestProfile extends string,
  TAccountHostProfile extends string,
  TAccountGuestReputation extends string,
  TAccountBooking extends string,
  TAccountBookingDays extends string,
  TAccountBookingDaysNext extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountHostTokenAccount extends string,
  TAccountPlatformVault extends string,
  TAccountMint extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: GuestCancelBookingCrossYearAsyncInput<
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountGuestReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  GuestCancelBookingCrossYearInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountGuestReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    guestProfile: { value: input.guestProfile ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    guestReputation: { value: input.guestReputation ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    bookingDaysNext: { value: input.bookingDaysNext ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    hostTokenAccount: {
      value: input.hostTokenAccount ?? null,
      isWritable: true,
    },
    platformVault: { value: input.platformVault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.escrowTokenAccount.value) {
    accounts.escrowTokenAccount.value = await findEscrowTokenAccountPda({
      booking: getAddressFromResolvedInstructionAccount(
        "booking",
        accounts.booking.value,
      ),
    });
  }
  if (!accounts.cpiAuthority.value) {
    accounts.cpiAuthority.value = await findCpiAuthorityPda();
  }
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("caller", accounts.caller),
      getAccountMeta("guestProfile", accounts.guestProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("guestReputation", accounts.guestReputation),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("bookingDaysNext", accounts.bookingDaysNext),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta("hostTokenAccount", accounts.hostTokenAccount),
      getAccountMeta("platformVault", accounts.platformVault),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getGuestCancelBookingCrossYearInstructionDataEncoder().encode({}),
    programAddress,
  } as GuestCancelBookingCrossYearInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountGuestReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >);
}

export type GuestCancelBookingCrossYearInput<
  TAccountCaller extends string = string,
  TAccountGuestProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountGuestReputation extends string = string,
  TAccountBooking extends string = string,
  TAccountBookingDays extends string = string,
  TAccountBookingDaysNext extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountHostTokenAccount extends string = string,
  TAccountPlatformVault extends string = string,
  TAccountMint extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  caller: TransactionSigner<TAccountCaller>;
  guestProfile: Address<TAccountGuestProfile>;
  hostProfile: Address<TAccountHostProfile>;
  guestReputation: Address<TAccountGuestReputation>;
  booking: Address<TAccountBooking>;
  /** In the future, property will store config data for slashing guest cancelation */
  bookingDays: Address<TAccountBookingDays>;
  /** Availability bitmap for the following year — released on cancellation. */
  bookingDaysNext: Address<TAccountBookingDaysNext>;
  globalConfig: Address<TAccountGlobalConfig>;
  escrowTokenAccount: Address<TAccountEscrowTokenAccount>;
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  hostTokenAccount: Address<TAccountHostTokenAccount>;
  platformVault: Address<TAccountPlatformVault>;
  mint: Address<TAccountMint>;
  /** stayke-core. */
  cpiAuthority: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getGuestCancelBookingCrossYearInstruction<
  TAccountCaller extends string,
  TAccountGuestProfile extends string,
  TAccountHostProfile extends string,
  TAccountGuestReputation extends string,
  TAccountBooking extends string,
  TAccountBookingDays extends string,
  TAccountBookingDaysNext extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountHostTokenAccount extends string,
  TAccountPlatformVault extends string,
  TAccountMint extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: GuestCancelBookingCrossYearInput<
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountGuestReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): GuestCancelBookingCrossYearInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountGuestProfile,
  TAccountHostProfile,
  TAccountGuestReputation,
  TAccountBooking,
  TAccountBookingDays,
  TAccountBookingDaysNext,
  TAccountGlobalConfig,
  TAccountEscrowTokenAccount,
  TAccountGuestTokenAccount,
  TAccountHostTokenAccount,
  TAccountPlatformVault,
  TAccountMint,
  TAccountCpiAuthority,
  TAccountStaykeCoreProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    guestProfile: { value: input.guestProfile ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    guestReputation: { value: input.guestReputation ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    bookingDaysNext: { value: input.bookingDaysNext ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    hostTokenAccount: {
      value: input.hostTokenAccount ?? null,
      isWritable: true,
    },
    platformVault: { value: input.platformVault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("caller", accounts.caller),
      getAccountMeta("guestProfile", accounts.guestProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("guestReputation", accounts.guestReputation),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("bookingDaysNext", accounts.bookingDaysNext),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta("hostTokenAccount", accounts.hostTokenAccount),
      getAccountMeta("platformVault", accounts.platformVault),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getGuestCancelBookingCrossYearInstructionDataEncoder().encode({}),
    programAddress,
  } as GuestCancelBookingCrossYearInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountGuestReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountHostTokenAccount,
    TAccountPlatformVault,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram,
    TAccountTokenProgram
  >);
}

export type ParsedGuestCancelBookingCrossYearInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    caller: TAccountMetas[0];
    guestProfile: TAccountMetas[1];
    hostProfile: TAccountMetas[2];
    guestReputation: TAccountMetas[3];
    booking: TAccountMetas[4];
    /** In the future, property will store config data for slashing guest cancelation */
    bookingDays: TAccountMetas[5];
    /** Availability bitmap for the following year — released on cancellation. */
    bookingDaysNext: TAccountMetas[6];
    globalConfig: TAccountMetas[7];
    escrowTokenAccount: TAccountMetas[8];
    guestTokenAccount: TAccountMetas[9];
    hostTokenAccount: TAccountMetas[10];
    platformVault: TAccountMetas[11];
    mint: TAccountMetas[12];
    /** stayke-core. */
    cpiAuthority: TAccountMetas[13];
    staykeCoreProgram: TAccountMetas[14];
    tokenProgram: TAccountMetas[15];
  };
  data: GuestCancelBookingCrossYearInstructionData;
};

export function parseGuestCancelBookingCrossYearInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedGuestCancelBookingCrossYearInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 16) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 16,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      guestProfile: getNextAccount(),
      hostProfile: getNextAccount(),
      guestReputation: getNextAccount(),
      booking: getNextAccount(),
      bookingDays: getNextAccount(),
      bookingDaysNext: getNextAccount(),
      globalConfig: getNextAccount(),
      escrowTokenAccount: getNextAccount(),
      guestTokenAccount: getNextAccount(),
      hostTokenAccount: getNextAccount(),
      platformVault: getNextAccount(),
      mint: getNextAccount(),
      cpiAuthority: getNextAccount(),
      staykeCoreProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getGuestCancelBookingCrossYearInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
