/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const HOST_REJECT_BOOKING_CROSS_YEAR_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([123, 241, 114, 228, 149, 154, 172, 11]);

export function getHostRejectBookingCrossYearDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    HOST_REJECT_BOOKING_CROSS_YEAR_DISCRIMINATOR,
  );
}

export type HostRejectBookingCrossYearInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountHost extends string | AccountMeta<string> = string,
  TAccountHostProfile extends string | AccountMeta<string> = string,
  TAccountGuest extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountBookingDays extends string | AccountMeta<string> = string,
  TAccountBookingDaysNext extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountHost extends string
        ? ReadonlySignerAccount<TAccountHost> & AccountSignerMeta<TAccountHost>
        : TAccountHost,
      TAccountHostProfile extends string
        ? ReadonlyAccount<TAccountHostProfile>
        : TAccountHostProfile,
      TAccountGuest extends string
        ? WritableAccount<TAccountGuest>
        : TAccountGuest,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountBookingDays extends string
        ? WritableAccount<TAccountBookingDays>
        : TAccountBookingDays,
      TAccountBookingDaysNext extends string
        ? WritableAccount<TAccountBookingDaysNext>
        : TAccountBookingDaysNext,
      ...TRemainingAccounts,
    ]
  >;

export type HostRejectBookingCrossYearInstructionData = {
  discriminator: ReadonlyUint8Array;
  checkIn: bigint;
};

export type HostRejectBookingCrossYearInstructionDataArgs = {
  checkIn: number | bigint;
};

export function getHostRejectBookingCrossYearInstructionDataEncoder(): FixedSizeEncoder<HostRejectBookingCrossYearInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["checkIn", getI64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: HOST_REJECT_BOOKING_CROSS_YEAR_DISCRIMINATOR,
    }),
  );
}

export function getHostRejectBookingCrossYearInstructionDataDecoder(): FixedSizeDecoder<HostRejectBookingCrossYearInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["checkIn", getI64Decoder()],
  ]);
}

export function getHostRejectBookingCrossYearInstructionDataCodec(): FixedSizeCodec<
  HostRejectBookingCrossYearInstructionDataArgs,
  HostRejectBookingCrossYearInstructionData
> {
  return combineCodec(
    getHostRejectBookingCrossYearInstructionDataEncoder(),
    getHostRejectBookingCrossYearInstructionDataDecoder(),
  );
}

export type HostRejectBookingCrossYearAsyncInput<
  TAccountPayer extends string = string,
  TAccountHost extends string = string,
  TAccountHostProfile extends string = string,
  TAccountGuest extends string = string,
  TAccountBooking extends string = string,
  TAccountBookingDays extends string = string,
  TAccountBookingDaysNext extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  host: TransactionSigner<TAccountHost>;
  hostProfile?: Address<TAccountHostProfile>;
  guest: Address<TAccountGuest>;
  booking: Address<TAccountBooking>;
  bookingDays: Address<TAccountBookingDays>;
  bookingDaysNext: Address<TAccountBookingDaysNext>;
  checkIn: HostRejectBookingCrossYearInstructionDataArgs["checkIn"];
};

export async function getHostRejectBookingCrossYearInstructionAsync<
  TAccountPayer extends string,
  TAccountHost extends string,
  TAccountHostProfile extends string,
  TAccountGuest extends string,
  TAccountBooking extends string,
  TAccountBookingDays extends string,
  TAccountBookingDaysNext extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: HostRejectBookingCrossYearAsyncInput<
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  HostRejectBookingCrossYearInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    host: { value: input.host ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    guest: { value: input.guest ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    bookingDaysNext: { value: input.bookingDaysNext ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.hostProfile.value) {
    accounts.hostProfile.value = await getProgramDerivedAddress({
      programAddress:
        "8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP" as Address<"8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            117, 115, 101, 114, 95, 112, 114, 111, 102, 105, 108, 101,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("host", accounts.host.value),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("host", accounts.host),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("guest", accounts.guest),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("bookingDaysNext", accounts.bookingDaysNext),
    ],
    data: getHostRejectBookingCrossYearInstructionDataEncoder().encode(
      args as HostRejectBookingCrossYearInstructionDataArgs,
    ),
    programAddress,
  } as HostRejectBookingCrossYearInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext
  >);
}

export type HostRejectBookingCrossYearInput<
  TAccountPayer extends string = string,
  TAccountHost extends string = string,
  TAccountHostProfile extends string = string,
  TAccountGuest extends string = string,
  TAccountBooking extends string = string,
  TAccountBookingDays extends string = string,
  TAccountBookingDaysNext extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  host: TransactionSigner<TAccountHost>;
  hostProfile: Address<TAccountHostProfile>;
  guest: Address<TAccountGuest>;
  booking: Address<TAccountBooking>;
  bookingDays: Address<TAccountBookingDays>;
  bookingDaysNext: Address<TAccountBookingDaysNext>;
  checkIn: HostRejectBookingCrossYearInstructionDataArgs["checkIn"];
};

export function getHostRejectBookingCrossYearInstruction<
  TAccountPayer extends string,
  TAccountHost extends string,
  TAccountHostProfile extends string,
  TAccountGuest extends string,
  TAccountBooking extends string,
  TAccountBookingDays extends string,
  TAccountBookingDaysNext extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: HostRejectBookingCrossYearInput<
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext
  >,
  config?: { programAddress?: TProgramAddress },
): HostRejectBookingCrossYearInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountHost,
  TAccountHostProfile,
  TAccountGuest,
  TAccountBooking,
  TAccountBookingDays,
  TAccountBookingDaysNext
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    host: { value: input.host ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    guest: { value: input.guest ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    bookingDaysNext: { value: input.bookingDaysNext ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("host", accounts.host),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("guest", accounts.guest),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("bookingDaysNext", accounts.bookingDaysNext),
    ],
    data: getHostRejectBookingCrossYearInstructionDataEncoder().encode(
      args as HostRejectBookingCrossYearInstructionDataArgs,
    ),
    programAddress,
  } as HostRejectBookingCrossYearInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext
  >);
}

export type ParsedHostRejectBookingCrossYearInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    host: TAccountMetas[1];
    hostProfile: TAccountMetas[2];
    guest: TAccountMetas[3];
    booking: TAccountMetas[4];
    bookingDays: TAccountMetas[5];
    bookingDaysNext: TAccountMetas[6];
  };
  data: HostRejectBookingCrossYearInstructionData;
};

export function parseHostRejectBookingCrossYearInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedHostRejectBookingCrossYearInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 7,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      host: getNextAccount(),
      hostProfile: getNextAccount(),
      guest: getNextAccount(),
      booking: getNextAccount(),
      bookingDays: getNextAccount(),
      bookingDaysNext: getNextAccount(),
    },
    data: getHostRejectBookingCrossYearInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
