/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findEscrowTokenAccountPda } from "../pdas";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const HOST_REJECT_BOOKING_CROSS_YEAR_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([123, 241, 114, 228, 149, 154, 172, 11]);

export function getHostRejectBookingCrossYearDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    HOST_REJECT_BOOKING_CROSS_YEAR_DISCRIMINATOR,
  );
}

export type HostRejectBookingCrossYearInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountHost extends string | AccountMeta<string> = string,
  TAccountHostProfile extends string | AccountMeta<string> = string,
  TAccountGuest extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountBookingDays extends string | AccountMeta<string> = string,
  TAccountBookingDaysNext extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountEscrowTokenAccount extends string | AccountMeta<string> = string,
  TAccountGuestTokenAccount extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountHost extends string
        ? ReadonlySignerAccount<TAccountHost> & AccountSignerMeta<TAccountHost>
        : TAccountHost,
      TAccountHostProfile extends string
        ? ReadonlyAccount<TAccountHostProfile>
        : TAccountHostProfile,
      TAccountGuest extends string
        ? ReadonlyAccount<TAccountGuest>
        : TAccountGuest,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountBookingDays extends string
        ? WritableAccount<TAccountBookingDays>
        : TAccountBookingDays,
      TAccountBookingDaysNext extends string
        ? WritableAccount<TAccountBookingDaysNext>
        : TAccountBookingDaysNext,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountEscrowTokenAccount extends string
        ? WritableAccount<TAccountEscrowTokenAccount>
        : TAccountEscrowTokenAccount,
      TAccountGuestTokenAccount extends string
        ? WritableAccount<TAccountGuestTokenAccount>
        : TAccountGuestTokenAccount,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type HostRejectBookingCrossYearInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type HostRejectBookingCrossYearInstructionDataArgs = {};

export function getHostRejectBookingCrossYearInstructionDataEncoder(): FixedSizeEncoder<HostRejectBookingCrossYearInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: HOST_REJECT_BOOKING_CROSS_YEAR_DISCRIMINATOR,
    }),
  );
}

export function getHostRejectBookingCrossYearInstructionDataDecoder(): FixedSizeDecoder<HostRejectBookingCrossYearInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getHostRejectBookingCrossYearInstructionDataCodec(): FixedSizeCodec<
  HostRejectBookingCrossYearInstructionDataArgs,
  HostRejectBookingCrossYearInstructionData
> {
  return combineCodec(
    getHostRejectBookingCrossYearInstructionDataEncoder(),
    getHostRejectBookingCrossYearInstructionDataDecoder(),
  );
}

export type HostRejectBookingCrossYearAsyncInput<
  TAccountPayer extends string = string,
  TAccountHost extends string = string,
  TAccountHostProfile extends string = string,
  TAccountGuest extends string = string,
  TAccountBooking extends string = string,
  TAccountBookingDays extends string = string,
  TAccountBookingDaysNext extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountMint extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  host: TransactionSigner<TAccountHost>;
  hostProfile?: Address<TAccountHostProfile>;
  guest: Address<TAccountGuest>;
  booking: Address<TAccountBooking>;
  bookingDays: Address<TAccountBookingDays>;
  bookingDaysNext: Address<TAccountBookingDaysNext>;
  globalConfig?: Address<TAccountGlobalConfig>;
  escrowTokenAccount?: Address<TAccountEscrowTokenAccount>;
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  mint: Address<TAccountMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getHostRejectBookingCrossYearInstructionAsync<
  TAccountPayer extends string,
  TAccountHost extends string,
  TAccountHostProfile extends string,
  TAccountGuest extends string,
  TAccountBooking extends string,
  TAccountBookingDays extends string,
  TAccountBookingDaysNext extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountMint extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: HostRejectBookingCrossYearAsyncInput<
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  HostRejectBookingCrossYearInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    host: { value: input.host ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    guest: { value: input.guest ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    bookingDaysNext: { value: input.bookingDaysNext ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.hostProfile.value) {
    accounts.hostProfile.value = await getProgramDerivedAddress({
      programAddress:
        "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            117, 115, 101, 114, 95, 112, 114, 111, 102, 105, 108, 101,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("host", accounts.host.value),
        ),
      ],
    });
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.escrowTokenAccount.value) {
    accounts.escrowTokenAccount.value = await findEscrowTokenAccountPda({
      booking: getAddressFromResolvedInstructionAccount(
        "booking",
        accounts.booking.value,
      ),
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("host", accounts.host),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("guest", accounts.guest),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("bookingDaysNext", accounts.bookingDaysNext),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getHostRejectBookingCrossYearInstructionDataEncoder().encode({}),
    programAddress,
  } as HostRejectBookingCrossYearInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountTokenProgram
  >);
}

export type HostRejectBookingCrossYearInput<
  TAccountPayer extends string = string,
  TAccountHost extends string = string,
  TAccountHostProfile extends string = string,
  TAccountGuest extends string = string,
  TAccountBooking extends string = string,
  TAccountBookingDays extends string = string,
  TAccountBookingDaysNext extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountMint extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  host: TransactionSigner<TAccountHost>;
  hostProfile: Address<TAccountHostProfile>;
  guest: Address<TAccountGuest>;
  booking: Address<TAccountBooking>;
  bookingDays: Address<TAccountBookingDays>;
  bookingDaysNext: Address<TAccountBookingDaysNext>;
  globalConfig: Address<TAccountGlobalConfig>;
  escrowTokenAccount: Address<TAccountEscrowTokenAccount>;
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  mint: Address<TAccountMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getHostRejectBookingCrossYearInstruction<
  TAccountPayer extends string,
  TAccountHost extends string,
  TAccountHostProfile extends string,
  TAccountGuest extends string,
  TAccountBooking extends string,
  TAccountBookingDays extends string,
  TAccountBookingDaysNext extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountMint extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: HostRejectBookingCrossYearInput<
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): HostRejectBookingCrossYearInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountHost,
  TAccountHostProfile,
  TAccountGuest,
  TAccountBooking,
  TAccountBookingDays,
  TAccountBookingDaysNext,
  TAccountGlobalConfig,
  TAccountEscrowTokenAccount,
  TAccountGuestTokenAccount,
  TAccountMint,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    host: { value: input.host ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    guest: { value: input.guest ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    bookingDaysNext: { value: input.bookingDaysNext ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("host", accounts.host),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("guest", accounts.guest),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("bookingDaysNext", accounts.bookingDaysNext),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getHostRejectBookingCrossYearInstructionDataEncoder().encode({}),
    programAddress,
  } as HostRejectBookingCrossYearInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountGuest,
    TAccountBooking,
    TAccountBookingDays,
    TAccountBookingDaysNext,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountTokenProgram
  >);
}

export type ParsedHostRejectBookingCrossYearInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    host: TAccountMetas[1];
    hostProfile: TAccountMetas[2];
    guest: TAccountMetas[3];
    booking: TAccountMetas[4];
    bookingDays: TAccountMetas[5];
    bookingDaysNext: TAccountMetas[6];
    globalConfig: TAccountMetas[7];
    escrowTokenAccount: TAccountMetas[8];
    guestTokenAccount: TAccountMetas[9];
    mint: TAccountMetas[10];
    tokenProgram: TAccountMetas[11];
  };
  data: HostRejectBookingCrossYearInstructionData;
};

export function parseHostRejectBookingCrossYearInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedHostRejectBookingCrossYearInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 12,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      host: getNextAccount(),
      hostProfile: getNextAccount(),
      guest: getNextAccount(),
      booking: getNextAccount(),
      bookingDays: getNextAccount(),
      bookingDaysNext: getNextAccount(),
      globalConfig: getNextAccount(),
      escrowTokenAccount: getNextAccount(),
      guestTokenAccount: getNextAccount(),
      mint: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getHostRejectBookingCrossYearInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
