/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findEscrowConfigPda } from "../pdas";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const HOST_ACCEPT_BOOKING_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([7, 61, 21, 168, 166, 46, 200, 76]);

export function getHostAcceptBookingDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    HOST_ACCEPT_BOOKING_DISCRIMINATOR,
  );
}

export type HostAcceptBookingInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountHost extends string | AccountMeta<string> = string,
  TAccountHostProfile extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountEscrowConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountHost extends string
        ? ReadonlySignerAccount<TAccountHost> & AccountSignerMeta<TAccountHost>
        : TAccountHost,
      TAccountHostProfile extends string
        ? ReadonlyAccount<TAccountHostProfile>
        : TAccountHostProfile,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountEscrowConfig extends string
        ? ReadonlyAccount<TAccountEscrowConfig>
        : TAccountEscrowConfig,
      ...TRemainingAccounts,
    ]
  >;

export type HostAcceptBookingInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type HostAcceptBookingInstructionDataArgs = {};

export function getHostAcceptBookingInstructionDataEncoder(): FixedSizeEncoder<HostAcceptBookingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: HOST_ACCEPT_BOOKING_DISCRIMINATOR }),
  );
}

export function getHostAcceptBookingInstructionDataDecoder(): FixedSizeDecoder<HostAcceptBookingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getHostAcceptBookingInstructionDataCodec(): FixedSizeCodec<
  HostAcceptBookingInstructionDataArgs,
  HostAcceptBookingInstructionData
> {
  return combineCodec(
    getHostAcceptBookingInstructionDataEncoder(),
    getHostAcceptBookingInstructionDataDecoder(),
  );
}

export type HostAcceptBookingAsyncInput<
  TAccountPayer extends string = string,
  TAccountHost extends string = string,
  TAccountHostProfile extends string = string,
  TAccountBooking extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowConfig extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  host: TransactionSigner<TAccountHost>;
  hostProfile?: Address<TAccountHostProfile>;
  booking: Address<TAccountBooking>;
  globalConfig?: Address<TAccountGlobalConfig>;
  escrowConfig?: Address<TAccountEscrowConfig>;
};

export async function getHostAcceptBookingInstructionAsync<
  TAccountPayer extends string,
  TAccountHost extends string,
  TAccountHostProfile extends string,
  TAccountBooking extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowConfig extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: HostAcceptBookingAsyncInput<
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  HostAcceptBookingInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    host: { value: input.host ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowConfig: { value: input.escrowConfig ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.hostProfile.value) {
    accounts.hostProfile.value = await getProgramDerivedAddress({
      programAddress:
        "8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP" as Address<"8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            117, 115, 101, 114, 95, 112, 114, 111, 102, 105, 108, 101,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("host", accounts.host.value),
        ),
      ],
    });
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW" as Address<"2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.escrowConfig.value) {
    accounts.escrowConfig.value = await findEscrowConfigPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("host", accounts.host),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowConfig", accounts.escrowConfig),
    ],
    data: getHostAcceptBookingInstructionDataEncoder().encode({}),
    programAddress,
  } as HostAcceptBookingInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig
  >);
}

export type HostAcceptBookingInput<
  TAccountPayer extends string = string,
  TAccountHost extends string = string,
  TAccountHostProfile extends string = string,
  TAccountBooking extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowConfig extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  host: TransactionSigner<TAccountHost>;
  hostProfile: Address<TAccountHostProfile>;
  booking: Address<TAccountBooking>;
  globalConfig: Address<TAccountGlobalConfig>;
  escrowConfig: Address<TAccountEscrowConfig>;
};

export function getHostAcceptBookingInstruction<
  TAccountPayer extends string,
  TAccountHost extends string,
  TAccountHostProfile extends string,
  TAccountBooking extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowConfig extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: HostAcceptBookingInput<
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig
  >,
  config?: { programAddress?: TProgramAddress },
): HostAcceptBookingInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountHost,
  TAccountHostProfile,
  TAccountBooking,
  TAccountGlobalConfig,
  TAccountEscrowConfig
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    host: { value: input.host ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    booking: { value: input.booking ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowConfig: { value: input.escrowConfig ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("host", accounts.host),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowConfig", accounts.escrowConfig),
    ],
    data: getHostAcceptBookingInstructionDataEncoder().encode({}),
    programAddress,
  } as HostAcceptBookingInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHost,
    TAccountHostProfile,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountEscrowConfig
  >);
}

export type ParsedHostAcceptBookingInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    host: TAccountMetas[1];
    hostProfile: TAccountMetas[2];
    booking: TAccountMetas[3];
    globalConfig: TAccountMetas[4];
    escrowConfig: TAccountMetas[5];
  };
  data: HostAcceptBookingInstructionData;
};

export function parseHostAcceptBookingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedHostAcceptBookingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      host: getNextAccount(),
      hostProfile: getNextAccount(),
      booking: getNextAccount(),
      globalConfig: getNextAccount(),
      escrowConfig: getNextAccount(),
    },
    data: getHostAcceptBookingInstructionDataDecoder().decode(instruction.data),
  };
}
