/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findCpiAuthorityPda, findEscrowTokenAccountPda } from "../pdas";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const HOST_CANCEL_BOOKING_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([115, 30, 3, 185, 98, 215, 78, 155]);

export function getHostCancelBookingDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    HOST_CANCEL_BOOKING_DISCRIMINATOR,
  );
}

export type HostCancelBookingInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountGuestProfile extends string | AccountMeta<string> = string,
  TAccountHostProfile extends string | AccountMeta<string> = string,
  TAccountHostReputation extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountBookingDays extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountEscrowTokenAccount extends string | AccountMeta<string> = string,
  TAccountGuestTokenAccount extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TAccountTreasuryConfig extends string | AccountMeta<string> = string,
  TAccountTreasuryVault extends string | AccountMeta<string> = string,
  TAccountTreasuryPda extends string | AccountMeta<string> = string,
  TAccountStaykeCoreProgram extends string | AccountMeta<string> =
    "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm",
  TAccountStaykeTreasuryProgram extends string | AccountMeta<string> =
    "HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? WritableSignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountGuestProfile extends string
        ? ReadonlyAccount<TAccountGuestProfile>
        : TAccountGuestProfile,
      TAccountHostProfile extends string
        ? WritableAccount<TAccountHostProfile>
        : TAccountHostProfile,
      TAccountHostReputation extends string
        ? WritableAccount<TAccountHostReputation>
        : TAccountHostReputation,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountBookingDays extends string
        ? WritableAccount<TAccountBookingDays>
        : TAccountBookingDays,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountEscrowTokenAccount extends string
        ? WritableAccount<TAccountEscrowTokenAccount>
        : TAccountEscrowTokenAccount,
      TAccountGuestTokenAccount extends string
        ? WritableAccount<TAccountGuestTokenAccount>
        : TAccountGuestTokenAccount,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountCpiAuthority extends string
        ? ReadonlyAccount<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      TAccountTreasuryConfig extends string
        ? ReadonlyAccount<TAccountTreasuryConfig>
        : TAccountTreasuryConfig,
      TAccountTreasuryVault extends string
        ? WritableAccount<TAccountTreasuryVault>
        : TAccountTreasuryVault,
      TAccountTreasuryPda extends string
        ? ReadonlyAccount<TAccountTreasuryPda>
        : TAccountTreasuryPda,
      TAccountStaykeCoreProgram extends string
        ? ReadonlyAccount<TAccountStaykeCoreProgram>
        : TAccountStaykeCoreProgram,
      TAccountStaykeTreasuryProgram extends string
        ? ReadonlyAccount<TAccountStaykeTreasuryProgram>
        : TAccountStaykeTreasuryProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type HostCancelBookingInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type HostCancelBookingInstructionDataArgs = {};

export function getHostCancelBookingInstructionDataEncoder(): FixedSizeEncoder<HostCancelBookingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: HOST_CANCEL_BOOKING_DISCRIMINATOR }),
  );
}

export function getHostCancelBookingInstructionDataDecoder(): FixedSizeDecoder<HostCancelBookingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getHostCancelBookingInstructionDataCodec(): FixedSizeCodec<
  HostCancelBookingInstructionDataArgs,
  HostCancelBookingInstructionData
> {
  return combineCodec(
    getHostCancelBookingInstructionDataEncoder(),
    getHostCancelBookingInstructionDataDecoder(),
  );
}

export type HostCancelBookingAsyncInput<
  TAccountCaller extends string = string,
  TAccountGuestProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountHostReputation extends string = string,
  TAccountBooking extends string = string,
  TAccountBookingDays extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountMint extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountTreasuryConfig extends string = string,
  TAccountTreasuryVault extends string = string,
  TAccountTreasuryPda extends string = string,
  TAccountStaykeCoreProgram extends string = string,
  TAccountStaykeTreasuryProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /**
   * The host of the booking. Validated against the host profile and also
   * receives the escrow account rent on closure.
   */
  caller: TransactionSigner<TAccountCaller>;
  /**
   * The guest's UserProfile — anchors the refund destination to the guest's
   * identity stored in the booking.
   */
  guestProfile: Address<TAccountGuestProfile>;
  /** The host's UserProfile — mutable for the deposit slash. */
  hostProfile: Address<TAccountHostProfile>;
  /** The host's ReputationProfile — mutable for `host_cancellations`. */
  hostReputation: Address<TAccountHostReputation>;
  booking: Address<TAccountBooking>;
  /**
   * The listing the booking belongs to — validated against `booking.property`.
   * The property's availability bitmap for the check-in year — the reserved
   * days are released on cancellation.
   */
  bookingDays: Address<TAccountBookingDays>;
  globalConfig?: Address<TAccountGlobalConfig>;
  escrowTokenAccount?: Address<TAccountEscrowTokenAccount>;
  /**
   * The guest's USDC token account — destination for the refund and the
   * host's deposit slash, bound to the guest's authority.
   */
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  mint: Address<TAccountMint>;
  cpiAuthority?: Address<TAccountCpiAuthority>;
  treasuryConfig?: Address<TAccountTreasuryConfig>;
  /** Treasury vault holding user guarantee deposits. */
  treasuryVault: Address<TAccountTreasuryVault>;
  /** is re-validated inside stayke-treasury's penalize CPI. */
  treasuryPda: Address<TAccountTreasuryPda>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  staykeTreasuryProgram?: Address<TAccountStaykeTreasuryProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getHostCancelBookingInstructionAsync<
  TAccountCaller extends string,
  TAccountGuestProfile extends string,
  TAccountHostProfile extends string,
  TAccountHostReputation extends string,
  TAccountBooking extends string,
  TAccountBookingDays extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountMint extends string,
  TAccountCpiAuthority extends string,
  TAccountTreasuryConfig extends string,
  TAccountTreasuryVault extends string,
  TAccountTreasuryPda extends string,
  TAccountStaykeCoreProgram extends string,
  TAccountStaykeTreasuryProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: HostCancelBookingAsyncInput<
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountTreasuryConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  HostCancelBookingInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountTreasuryConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    guestProfile: { value: input.guestProfile ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: true },
    hostReputation: { value: input.hostReputation ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    treasuryConfig: { value: input.treasuryConfig ?? null, isWritable: false },
    treasuryVault: { value: input.treasuryVault ?? null, isWritable: true },
    treasuryPda: { value: input.treasuryPda ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
    staykeTreasuryProgram: {
      value: input.staykeTreasuryProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.escrowTokenAccount.value) {
    accounts.escrowTokenAccount.value = await findEscrowTokenAccountPda({
      booking: getAddressFromResolvedInstructionAccount(
        "booking",
        accounts.booking.value,
      ),
    });
  }
  if (!accounts.cpiAuthority.value) {
    accounts.cpiAuthority.value = await findCpiAuthorityPda();
  }
  if (!accounts.treasuryConfig.value) {
    accounts.treasuryConfig.value = await getProgramDerivedAddress({
      programAddress:
        "HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY" as Address<"HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 101, 97, 115, 117, 114, 121, 95, 99, 111, 110, 102, 105,
            103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }
  if (!accounts.staykeTreasuryProgram.value) {
    accounts.staykeTreasuryProgram.value =
      "HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY" as Address<"HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("caller", accounts.caller),
      getAccountMeta("guestProfile", accounts.guestProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("hostReputation", accounts.hostReputation),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("treasuryConfig", accounts.treasuryConfig),
      getAccountMeta("treasuryVault", accounts.treasuryVault),
      getAccountMeta("treasuryPda", accounts.treasuryPda),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
      getAccountMeta("staykeTreasuryProgram", accounts.staykeTreasuryProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getHostCancelBookingInstructionDataEncoder().encode({}),
    programAddress,
  } as HostCancelBookingInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountTreasuryConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >);
}

export type HostCancelBookingInput<
  TAccountCaller extends string = string,
  TAccountGuestProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountHostReputation extends string = string,
  TAccountBooking extends string = string,
  TAccountBookingDays extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountEscrowTokenAccount extends string = string,
  TAccountGuestTokenAccount extends string = string,
  TAccountMint extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountTreasuryConfig extends string = string,
  TAccountTreasuryVault extends string = string,
  TAccountTreasuryPda extends string = string,
  TAccountStaykeCoreProgram extends string = string,
  TAccountStaykeTreasuryProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /**
   * The host of the booking. Validated against the host profile and also
   * receives the escrow account rent on closure.
   */
  caller: TransactionSigner<TAccountCaller>;
  /**
   * The guest's UserProfile — anchors the refund destination to the guest's
   * identity stored in the booking.
   */
  guestProfile: Address<TAccountGuestProfile>;
  /** The host's UserProfile — mutable for the deposit slash. */
  hostProfile: Address<TAccountHostProfile>;
  /** The host's ReputationProfile — mutable for `host_cancellations`. */
  hostReputation: Address<TAccountHostReputation>;
  booking: Address<TAccountBooking>;
  /**
   * The listing the booking belongs to — validated against `booking.property`.
   * The property's availability bitmap for the check-in year — the reserved
   * days are released on cancellation.
   */
  bookingDays: Address<TAccountBookingDays>;
  globalConfig: Address<TAccountGlobalConfig>;
  escrowTokenAccount: Address<TAccountEscrowTokenAccount>;
  /**
   * The guest's USDC token account — destination for the refund and the
   * host's deposit slash, bound to the guest's authority.
   */
  guestTokenAccount: Address<TAccountGuestTokenAccount>;
  mint: Address<TAccountMint>;
  cpiAuthority: Address<TAccountCpiAuthority>;
  treasuryConfig: Address<TAccountTreasuryConfig>;
  /** Treasury vault holding user guarantee deposits. */
  treasuryVault: Address<TAccountTreasuryVault>;
  /** is re-validated inside stayke-treasury's penalize CPI. */
  treasuryPda: Address<TAccountTreasuryPda>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  staykeTreasuryProgram?: Address<TAccountStaykeTreasuryProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getHostCancelBookingInstruction<
  TAccountCaller extends string,
  TAccountGuestProfile extends string,
  TAccountHostProfile extends string,
  TAccountHostReputation extends string,
  TAccountBooking extends string,
  TAccountBookingDays extends string,
  TAccountGlobalConfig extends string,
  TAccountEscrowTokenAccount extends string,
  TAccountGuestTokenAccount extends string,
  TAccountMint extends string,
  TAccountCpiAuthority extends string,
  TAccountTreasuryConfig extends string,
  TAccountTreasuryVault extends string,
  TAccountTreasuryPda extends string,
  TAccountStaykeCoreProgram extends string,
  TAccountStaykeTreasuryProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: HostCancelBookingInput<
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountTreasuryConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): HostCancelBookingInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountGuestProfile,
  TAccountHostProfile,
  TAccountHostReputation,
  TAccountBooking,
  TAccountBookingDays,
  TAccountGlobalConfig,
  TAccountEscrowTokenAccount,
  TAccountGuestTokenAccount,
  TAccountMint,
  TAccountCpiAuthority,
  TAccountTreasuryConfig,
  TAccountTreasuryVault,
  TAccountTreasuryPda,
  TAccountStaykeCoreProgram,
  TAccountStaykeTreasuryProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    guestProfile: { value: input.guestProfile ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: true },
    hostReputation: { value: input.hostReputation ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    bookingDays: { value: input.bookingDays ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    escrowTokenAccount: {
      value: input.escrowTokenAccount ?? null,
      isWritable: true,
    },
    guestTokenAccount: {
      value: input.guestTokenAccount ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    treasuryConfig: { value: input.treasuryConfig ?? null, isWritable: false },
    treasuryVault: { value: input.treasuryVault ?? null, isWritable: true },
    treasuryPda: { value: input.treasuryPda ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
    staykeTreasuryProgram: {
      value: input.staykeTreasuryProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }
  if (!accounts.staykeTreasuryProgram.value) {
    accounts.staykeTreasuryProgram.value =
      "HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY" as Address<"HV16vUTaZ78bJP1CyH5KDWyx8NqS1MYSGdPkRsMcnSuY">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("caller", accounts.caller),
      getAccountMeta("guestProfile", accounts.guestProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("hostReputation", accounts.hostReputation),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("bookingDays", accounts.bookingDays),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("escrowTokenAccount", accounts.escrowTokenAccount),
      getAccountMeta("guestTokenAccount", accounts.guestTokenAccount),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("treasuryConfig", accounts.treasuryConfig),
      getAccountMeta("treasuryVault", accounts.treasuryVault),
      getAccountMeta("treasuryPda", accounts.treasuryPda),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
      getAccountMeta("staykeTreasuryProgram", accounts.staykeTreasuryProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getHostCancelBookingInstructionDataEncoder().encode({}),
    programAddress,
  } as HostCancelBookingInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountGuestProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountBookingDays,
    TAccountGlobalConfig,
    TAccountEscrowTokenAccount,
    TAccountGuestTokenAccount,
    TAccountMint,
    TAccountCpiAuthority,
    TAccountTreasuryConfig,
    TAccountTreasuryVault,
    TAccountTreasuryPda,
    TAccountStaykeCoreProgram,
    TAccountStaykeTreasuryProgram,
    TAccountTokenProgram
  >);
}

export type ParsedHostCancelBookingInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /**
     * The host of the booking. Validated against the host profile and also
     * receives the escrow account rent on closure.
     */
    caller: TAccountMetas[0];
    /**
     * The guest's UserProfile — anchors the refund destination to the guest's
     * identity stored in the booking.
     */
    guestProfile: TAccountMetas[1];
    /** The host's UserProfile — mutable for the deposit slash. */
    hostProfile: TAccountMetas[2];
    /** The host's ReputationProfile — mutable for `host_cancellations`. */
    hostReputation: TAccountMetas[3];
    booking: TAccountMetas[4];
    /**
     * The listing the booking belongs to — validated against `booking.property`.
     * The property's availability bitmap for the check-in year — the reserved
     * days are released on cancellation.
     */
    bookingDays: TAccountMetas[5];
    globalConfig: TAccountMetas[6];
    escrowTokenAccount: TAccountMetas[7];
    /**
     * The guest's USDC token account — destination for the refund and the
     * host's deposit slash, bound to the guest's authority.
     */
    guestTokenAccount: TAccountMetas[8];
    mint: TAccountMetas[9];
    cpiAuthority: TAccountMetas[10];
    treasuryConfig: TAccountMetas[11];
    /** Treasury vault holding user guarantee deposits. */
    treasuryVault: TAccountMetas[12];
    /** is re-validated inside stayke-treasury's penalize CPI. */
    treasuryPda: TAccountMetas[13];
    staykeCoreProgram: TAccountMetas[14];
    staykeTreasuryProgram: TAccountMetas[15];
    tokenProgram: TAccountMetas[16];
  };
  data: HostCancelBookingInstructionData;
};

export function parseHostCancelBookingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedHostCancelBookingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 17) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 17,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      guestProfile: getNextAccount(),
      hostProfile: getNextAccount(),
      hostReputation: getNextAccount(),
      booking: getNextAccount(),
      bookingDays: getNextAccount(),
      globalConfig: getNextAccount(),
      escrowTokenAccount: getNextAccount(),
      guestTokenAccount: getNextAccount(),
      mint: getNextAccount(),
      cpiAuthority: getNextAccount(),
      treasuryConfig: getNextAccount(),
      treasuryVault: getNextAccount(),
      treasuryPda: getNextAccount(),
      staykeCoreProgram: getNextAccount(),
      staykeTreasuryProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getHostCancelBookingInstructionDataDecoder().decode(instruction.data),
  };
}
