/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findCpiAuthorityPda } from "../pdas";
import { STAYKE_ESCROW_PROGRAM_ADDRESS } from "../programs";

export const REVIEW_COMPLETED_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([196, 242, 133, 147, 126, 125, 244, 151]);

export function getReviewCompletedDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REVIEW_COMPLETED_DISCRIMINATOR,
  );
}

export type ReviewCompletedInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountClient extends string | AccountMeta<string> = string,
  TAccountClientProfile extends string | AccountMeta<string> = string,
  TAccountHostProfile extends string | AccountMeta<string> = string,
  TAccountHostReputation extends string | AccountMeta<string> = string,
  TAccountBooking extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TAccountStaykeCoreProgram extends string | AccountMeta<string> =
    "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountClient extends string
        ? ReadonlySignerAccount<TAccountClient> &
            AccountSignerMeta<TAccountClient>
        : TAccountClient,
      TAccountClientProfile extends string
        ? ReadonlyAccount<TAccountClientProfile>
        : TAccountClientProfile,
      TAccountHostProfile extends string
        ? ReadonlyAccount<TAccountHostProfile>
        : TAccountHostProfile,
      TAccountHostReputation extends string
        ? WritableAccount<TAccountHostReputation>
        : TAccountHostReputation,
      TAccountBooking extends string
        ? WritableAccount<TAccountBooking>
        : TAccountBooking,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountCpiAuthority extends string
        ? ReadonlyAccount<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      TAccountStaykeCoreProgram extends string
        ? ReadonlyAccount<TAccountStaykeCoreProgram>
        : TAccountStaykeCoreProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ReviewCompletedInstructionData = {
  discriminator: ReadonlyUint8Array;
  score: number;
};

export type ReviewCompletedInstructionDataArgs = { score: number };

export function getReviewCompletedInstructionDataEncoder(): FixedSizeEncoder<ReviewCompletedInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["score", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: REVIEW_COMPLETED_DISCRIMINATOR }),
  );
}

export function getReviewCompletedInstructionDataDecoder(): FixedSizeDecoder<ReviewCompletedInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["score", getU8Decoder()],
  ]);
}

export function getReviewCompletedInstructionDataCodec(): FixedSizeCodec<
  ReviewCompletedInstructionDataArgs,
  ReviewCompletedInstructionData
> {
  return combineCodec(
    getReviewCompletedInstructionDataEncoder(),
    getReviewCompletedInstructionDataDecoder(),
  );
}

export type ReviewCompletedAsyncInput<
  TAccountPayer extends string = string,
  TAccountClient extends string = string,
  TAccountClientProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountHostReputation extends string = string,
  TAccountBooking extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  client: TransactionSigner<TAccountClient>;
  clientProfile?: Address<TAccountClientProfile>;
  /** Host UserProfile (correct seed family). */
  hostProfile: Address<TAccountHostProfile>;
  /** Host ReputationProfile (correct seed family). */
  hostReputation: Address<TAccountHostReputation>;
  booking: Address<TAccountBooking>;
  globalConfig?: Address<TAccountGlobalConfig>;
  cpiAuthority?: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  score: ReviewCompletedInstructionDataArgs["score"];
};

export async function getReviewCompletedInstructionAsync<
  TAccountPayer extends string,
  TAccountClient extends string,
  TAccountClientProfile extends string,
  TAccountHostProfile extends string,
  TAccountHostReputation extends string,
  TAccountBooking extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: ReviewCompletedAsyncInput<
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ReviewCompletedInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    client: { value: input.client ?? null, isWritable: false },
    clientProfile: { value: input.clientProfile ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    hostReputation: { value: input.hostReputation ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.clientProfile.value) {
    accounts.clientProfile.value = await getProgramDerivedAddress({
      programAddress:
        "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            117, 115, 101, 114, 95, 112, 114, 111, 102, 105, 108, 101,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "client",
            accounts.client.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "29A2HXuDHX8WQoPnYbFP4DR4W6HjQTBDA2N5pCPZEFs4" as Address<"29A2HXuDHX8WQoPnYbFP4DR4W6HjQTBDA2N5pCPZEFs4">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.cpiAuthority.value) {
    accounts.cpiAuthority.value = await findCpiAuthorityPda();
  }
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("client", accounts.client),
      getAccountMeta("clientProfile", accounts.clientProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("hostReputation", accounts.hostReputation),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
    ],
    data: getReviewCompletedInstructionDataEncoder().encode(
      args as ReviewCompletedInstructionDataArgs,
    ),
    programAddress,
  } as ReviewCompletedInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >);
}

export type ReviewCompletedInput<
  TAccountPayer extends string = string,
  TAccountClient extends string = string,
  TAccountClientProfile extends string = string,
  TAccountHostProfile extends string = string,
  TAccountHostReputation extends string = string,
  TAccountBooking extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  client: TransactionSigner<TAccountClient>;
  clientProfile: Address<TAccountClientProfile>;
  /** Host UserProfile (correct seed family). */
  hostProfile: Address<TAccountHostProfile>;
  /** Host ReputationProfile (correct seed family). */
  hostReputation: Address<TAccountHostReputation>;
  booking: Address<TAccountBooking>;
  globalConfig: Address<TAccountGlobalConfig>;
  cpiAuthority: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  score: ReviewCompletedInstructionDataArgs["score"];
};

export function getReviewCompletedInstruction<
  TAccountPayer extends string,
  TAccountClient extends string,
  TAccountClientProfile extends string,
  TAccountHostProfile extends string,
  TAccountHostReputation extends string,
  TAccountBooking extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
>(
  input: ReviewCompletedInput<
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ReviewCompletedInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountClient,
  TAccountClientProfile,
  TAccountHostProfile,
  TAccountHostReputation,
  TAccountBooking,
  TAccountGlobalConfig,
  TAccountCpiAuthority,
  TAccountStaykeCoreProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_ESCROW_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    client: { value: input.client ?? null, isWritable: false },
    clientProfile: { value: input.clientProfile ?? null, isWritable: false },
    hostProfile: { value: input.hostProfile ?? null, isWritable: false },
    hostReputation: { value: input.hostReputation ?? null, isWritable: true },
    booking: { value: input.booking ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("client", accounts.client),
      getAccountMeta("clientProfile", accounts.clientProfile),
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("hostReputation", accounts.hostReputation),
      getAccountMeta("booking", accounts.booking),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
    ],
    data: getReviewCompletedInstructionDataEncoder().encode(
      args as ReviewCompletedInstructionDataArgs,
    ),
    programAddress,
  } as ReviewCompletedInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountClient,
    TAccountClientProfile,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountBooking,
    TAccountGlobalConfig,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >);
}

export type ParsedReviewCompletedInstruction<
  TProgram extends string = typeof STAYKE_ESCROW_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    client: TAccountMetas[1];
    clientProfile: TAccountMetas[2];
    /** Host UserProfile (correct seed family). */
    hostProfile: TAccountMetas[3];
    /** Host ReputationProfile (correct seed family). */
    hostReputation: TAccountMetas[4];
    booking: TAccountMetas[5];
    globalConfig: TAccountMetas[6];
    cpiAuthority: TAccountMetas[7];
    staykeCoreProgram: TAccountMetas[8];
  };
  data: ReviewCompletedInstructionData;
};

export function parseReviewCompletedInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedReviewCompletedInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      client: getNextAccount(),
      clientProfile: getNextAccount(),
      hostProfile: getNextAccount(),
      hostReputation: getNextAccount(),
      booking: getNextAccount(),
      globalConfig: getNextAccount(),
      cpiAuthority: getNextAccount(),
      staykeCoreProgram: getNextAccount(),
    },
    data: getReviewCompletedInstructionDataDecoder().decode(instruction.data),
  };
}
