/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findConfigPda,
  findCpiAuthorityPda,
  findUserProfilePda,
} from "../pdas";
import { STAYKE_TREASURY_PROGRAM_ADDRESS } from "../programs";

export const DEPOSIT_GUARANTEE_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([174, 44, 254, 65, 0, 155, 77, 55]);

export function getDepositGuaranteeDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DEPOSIT_GUARANTEE_DISCRIMINATOR,
  );
}

export type DepositGuaranteeInstruction<
  TProgram extends string = typeof STAYKE_TREASURY_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountSenderTokenAccount extends string | AccountMeta<string> = string,
  TAccountTreasuryVault extends string | AccountMeta<string> = string,
  TAccountUsdcMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountUserProfile extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TAccountStaykeCoreProgram extends string | AccountMeta<string> =
    "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountSenderTokenAccount extends string
        ? WritableAccount<TAccountSenderTokenAccount>
        : TAccountSenderTokenAccount,
      TAccountTreasuryVault extends string
        ? WritableAccount<TAccountTreasuryVault>
        : TAccountTreasuryVault,
      TAccountUsdcMint extends string
        ? ReadonlyAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountUserProfile extends string
        ? WritableAccount<TAccountUserProfile>
        : TAccountUserProfile,
      TAccountCpiAuthority extends string
        ? ReadonlyAccount<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      TAccountStaykeCoreProgram extends string
        ? ReadonlyAccount<TAccountStaykeCoreProgram>
        : TAccountStaykeCoreProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DepositGuaranteeInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type DepositGuaranteeInstructionDataArgs = { amount: number | bigint };

export function getDepositGuaranteeInstructionDataEncoder(): FixedSizeEncoder<DepositGuaranteeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: DEPOSIT_GUARANTEE_DISCRIMINATOR }),
  );
}

export function getDepositGuaranteeInstructionDataDecoder(): FixedSizeDecoder<DepositGuaranteeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getDepositGuaranteeInstructionDataCodec(): FixedSizeCodec<
  DepositGuaranteeInstructionDataArgs,
  DepositGuaranteeInstructionData
> {
  return combineCodec(
    getDepositGuaranteeInstructionDataEncoder(),
    getDepositGuaranteeInstructionDataDecoder(),
  );
}

export type DepositGuaranteeAsyncInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountSenderTokenAccount extends string = string,
  TAccountTreasuryVault extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountUserProfile extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  config?: Address<TAccountConfig>;
  globalConfig?: Address<TAccountGlobalConfig>;
  senderTokenAccount: Address<TAccountSenderTokenAccount>;
  treasuryVault: Address<TAccountTreasuryVault>;
  usdcMint: Address<TAccountUsdcMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  userProfile?: Address<TAccountUserProfile>;
  cpiAuthority?: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  amount: DepositGuaranteeInstructionDataArgs["amount"];
};

export async function getDepositGuaranteeInstructionAsync<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountGlobalConfig extends string,
  TAccountSenderTokenAccount extends string,
  TAccountTreasuryVault extends string,
  TAccountUsdcMint extends string,
  TAccountTokenProgram extends string,
  TAccountUserProfile extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_TREASURY_PROGRAM_ADDRESS,
>(
  input: DepositGuaranteeAsyncInput<
    TAccountSigner,
    TAccountConfig,
    TAccountGlobalConfig,
    TAccountSenderTokenAccount,
    TAccountTreasuryVault,
    TAccountUsdcMint,
    TAccountTokenProgram,
    TAccountUserProfile,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  DepositGuaranteeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountGlobalConfig,
    TAccountSenderTokenAccount,
    TAccountTreasuryVault,
    TAccountUsdcMint,
    TAccountTokenProgram,
    TAccountUserProfile,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_TREASURY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    senderTokenAccount: {
      value: input.senderTokenAccount ?? null,
      isWritable: true,
    },
    treasuryVault: { value: input.treasuryVault ?? null, isWritable: true },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    userProfile: { value: input.userProfile ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.userProfile.value) {
    accounts.userProfile.value = await findUserProfilePda({
      signer: getAddressFromResolvedInstructionAccount(
        "signer",
        accounts.signer.value,
      ),
    });
  }
  if (!accounts.cpiAuthority.value) {
    accounts.cpiAuthority.value = await findCpiAuthorityPda();
  }
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("senderTokenAccount", accounts.senderTokenAccount),
      getAccountMeta("treasuryVault", accounts.treasuryVault),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("userProfile", accounts.userProfile),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
    ],
    data: getDepositGuaranteeInstructionDataEncoder().encode(
      args as DepositGuaranteeInstructionDataArgs,
    ),
    programAddress,
  } as DepositGuaranteeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountGlobalConfig,
    TAccountSenderTokenAccount,
    TAccountTreasuryVault,
    TAccountUsdcMint,
    TAccountTokenProgram,
    TAccountUserProfile,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >);
}

export type DepositGuaranteeInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountSenderTokenAccount extends string = string,
  TAccountTreasuryVault extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountUserProfile extends string = string,
  TAccountCpiAuthority extends string = string,
  TAccountStaykeCoreProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  config: Address<TAccountConfig>;
  globalConfig: Address<TAccountGlobalConfig>;
  senderTokenAccount: Address<TAccountSenderTokenAccount>;
  treasuryVault: Address<TAccountTreasuryVault>;
  usdcMint: Address<TAccountUsdcMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  userProfile: Address<TAccountUserProfile>;
  cpiAuthority: Address<TAccountCpiAuthority>;
  staykeCoreProgram?: Address<TAccountStaykeCoreProgram>;
  amount: DepositGuaranteeInstructionDataArgs["amount"];
};

export function getDepositGuaranteeInstruction<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountGlobalConfig extends string,
  TAccountSenderTokenAccount extends string,
  TAccountTreasuryVault extends string,
  TAccountUsdcMint extends string,
  TAccountTokenProgram extends string,
  TAccountUserProfile extends string,
  TAccountCpiAuthority extends string,
  TAccountStaykeCoreProgram extends string,
  TProgramAddress extends Address = typeof STAYKE_TREASURY_PROGRAM_ADDRESS,
>(
  input: DepositGuaranteeInput<
    TAccountSigner,
    TAccountConfig,
    TAccountGlobalConfig,
    TAccountSenderTokenAccount,
    TAccountTreasuryVault,
    TAccountUsdcMint,
    TAccountTokenProgram,
    TAccountUserProfile,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >,
  config?: { programAddress?: TProgramAddress },
): DepositGuaranteeInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountConfig,
  TAccountGlobalConfig,
  TAccountSenderTokenAccount,
  TAccountTreasuryVault,
  TAccountUsdcMint,
  TAccountTokenProgram,
  TAccountUserProfile,
  TAccountCpiAuthority,
  TAccountStaykeCoreProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAYKE_TREASURY_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    senderTokenAccount: {
      value: input.senderTokenAccount ?? null,
      isWritable: true,
    },
    treasuryVault: { value: input.treasuryVault ?? null, isWritable: true },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    userProfile: { value: input.userProfile ?? null, isWritable: true },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
    staykeCoreProgram: {
      value: input.staykeCoreProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.staykeCoreProgram.value) {
    accounts.staykeCoreProgram.value =
      "2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm" as Address<"2u1JrVasLvuGR5s3n84p5yaitHU2PGa8VjWZ7P2Eescm">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("senderTokenAccount", accounts.senderTokenAccount),
      getAccountMeta("treasuryVault", accounts.treasuryVault),
      getAccountMeta("usdcMint", accounts.usdcMint),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("userProfile", accounts.userProfile),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
      getAccountMeta("staykeCoreProgram", accounts.staykeCoreProgram),
    ],
    data: getDepositGuaranteeInstructionDataEncoder().encode(
      args as DepositGuaranteeInstructionDataArgs,
    ),
    programAddress,
  } as DepositGuaranteeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountGlobalConfig,
    TAccountSenderTokenAccount,
    TAccountTreasuryVault,
    TAccountUsdcMint,
    TAccountTokenProgram,
    TAccountUserProfile,
    TAccountCpiAuthority,
    TAccountStaykeCoreProgram
  >);
}

export type ParsedDepositGuaranteeInstruction<
  TProgram extends string = typeof STAYKE_TREASURY_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    config: TAccountMetas[1];
    globalConfig: TAccountMetas[2];
    senderTokenAccount: TAccountMetas[3];
    treasuryVault: TAccountMetas[4];
    usdcMint: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
    userProfile: TAccountMetas[7];
    cpiAuthority: TAccountMetas[8];
    staykeCoreProgram: TAccountMetas[9];
  };
  data: DepositGuaranteeInstructionData;
};

export function parseDepositGuaranteeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedDepositGuaranteeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 10,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      config: getNextAccount(),
      globalConfig: getNextAccount(),
      senderTokenAccount: getNextAccount(),
      treasuryVault: getNextAccount(),
      usdcMint: getNextAccount(),
      tokenProgram: getNextAccount(),
      userProfile: getNextAccount(),
      cpiAuthority: getNextAccount(),
      staykeCoreProgram: getNextAccount(),
    },
    data: getDepositGuaranteeInstructionDataDecoder().decode(instruction.data),
  };
}
