/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type GlobalConfig = {
  authority: Address;
  minimumDeposit: bigint;
  feeBps: bigint;
  usdcMint: Address;
  isInitialized: boolean;
  /** Free operations before deposit is required */
  freeOps: number;
  /** Platform fee vault token account. */
  platformVault: Address;
  /** Bump of the platform vault authority PDA. */
  platformVaultBump: number;
  /** Stayke core program ID (CPI allowlist SoT). */
  coreProgram: Address;
  /** Stayke escrow program ID (CPI allowlist SoT). */
  escrowProgram: Address;
  /** Stayke disputes program ID (CPI allowlist SoT). */
  disputesProgram: Address;
  /** Stayke treasury program ID (CPI allowlist SoT). */
  treasuryProgram: Address;
  bump: number;
};

export type GlobalConfigArgs = {
  authority: Address;
  minimumDeposit: number | bigint;
  feeBps: number | bigint;
  usdcMint: Address;
  isInitialized: boolean;
  /** Free operations before deposit is required */
  freeOps: number;
  /** Platform fee vault token account. */
  platformVault: Address;
  /** Bump of the platform vault authority PDA. */
  platformVaultBump: number;
  /** Stayke core program ID (CPI allowlist SoT). */
  coreProgram: Address;
  /** Stayke escrow program ID (CPI allowlist SoT). */
  escrowProgram: Address;
  /** Stayke disputes program ID (CPI allowlist SoT). */
  disputesProgram: Address;
  /** Stayke treasury program ID (CPI allowlist SoT). */
  treasuryProgram: Address;
  bump: number;
};

export function getGlobalConfigEncoder(): FixedSizeEncoder<GlobalConfigArgs> {
  return getStructEncoder([
    ["authority", getAddressEncoder()],
    ["minimumDeposit", getU64Encoder()],
    ["feeBps", getU64Encoder()],
    ["usdcMint", getAddressEncoder()],
    ["isInitialized", getBooleanEncoder()],
    ["freeOps", getU8Encoder()],
    ["platformVault", getAddressEncoder()],
    ["platformVaultBump", getU8Encoder()],
    ["coreProgram", getAddressEncoder()],
    ["escrowProgram", getAddressEncoder()],
    ["disputesProgram", getAddressEncoder()],
    ["treasuryProgram", getAddressEncoder()],
    ["bump", getU8Encoder()],
  ]);
}

export function getGlobalConfigDecoder(): FixedSizeDecoder<GlobalConfig> {
  return getStructDecoder([
    ["authority", getAddressDecoder()],
    ["minimumDeposit", getU64Decoder()],
    ["feeBps", getU64Decoder()],
    ["usdcMint", getAddressDecoder()],
    ["isInitialized", getBooleanDecoder()],
    ["freeOps", getU8Decoder()],
    ["platformVault", getAddressDecoder()],
    ["platformVaultBump", getU8Decoder()],
    ["coreProgram", getAddressDecoder()],
    ["escrowProgram", getAddressDecoder()],
    ["disputesProgram", getAddressDecoder()],
    ["treasuryProgram", getAddressDecoder()],
    ["bump", getU8Decoder()],
  ]);
}

export function getGlobalConfigCodec(): FixedSizeCodec<
  GlobalConfigArgs,
  GlobalConfig
> {
  return combineCodec(getGlobalConfigEncoder(), getGlobalConfigDecoder());
}
