/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type ReputationProfile = {
  owner: Address;
  hostReviews: number;
  totalScoreHost: bigint;
  clientReviews: number;
  totalScoreClient: bigint;
  hostedStays: number;
  completedStays: number;
  hostCancellations: number;
  clientCancellations: number;
  hostCancellationsWithin48h: number;
  clientCancellationsWithin48h: number;
  lowInfractions: number;
  mediumInfractions: number;
  highInfractions: number;
  lastUpdated: bigint;
  bump: number;
};

export type ReputationProfileArgs = {
  owner: Address;
  hostReviews: number;
  totalScoreHost: number | bigint;
  clientReviews: number;
  totalScoreClient: number | bigint;
  hostedStays: number;
  completedStays: number;
  hostCancellations: number;
  clientCancellations: number;
  hostCancellationsWithin48h: number;
  clientCancellationsWithin48h: number;
  lowInfractions: number;
  mediumInfractions: number;
  highInfractions: number;
  lastUpdated: number | bigint;
  bump: number;
};

export function getReputationProfileEncoder(): FixedSizeEncoder<ReputationProfileArgs> {
  return getStructEncoder([
    ["owner", getAddressEncoder()],
    ["hostReviews", getU32Encoder()],
    ["totalScoreHost", getU64Encoder()],
    ["clientReviews", getU32Encoder()],
    ["totalScoreClient", getU64Encoder()],
    ["hostedStays", getU32Encoder()],
    ["completedStays", getU32Encoder()],
    ["hostCancellations", getU32Encoder()],
    ["clientCancellations", getU32Encoder()],
    ["hostCancellationsWithin48h", getU32Encoder()],
    ["clientCancellationsWithin48h", getU32Encoder()],
    ["lowInfractions", getU8Encoder()],
    ["mediumInfractions", getU8Encoder()],
    ["highInfractions", getU8Encoder()],
    ["lastUpdated", getI64Encoder()],
    ["bump", getU8Encoder()],
  ]);
}

export function getReputationProfileDecoder(): FixedSizeDecoder<ReputationProfile> {
  return getStructDecoder([
    ["owner", getAddressDecoder()],
    ["hostReviews", getU32Decoder()],
    ["totalScoreHost", getU64Decoder()],
    ["clientReviews", getU32Decoder()],
    ["totalScoreClient", getU64Decoder()],
    ["hostedStays", getU32Decoder()],
    ["completedStays", getU32Decoder()],
    ["hostCancellations", getU32Decoder()],
    ["clientCancellations", getU32Decoder()],
    ["hostCancellationsWithin48h", getU32Decoder()],
    ["clientCancellationsWithin48h", getU32Decoder()],
    ["lowInfractions", getU8Decoder()],
    ["mediumInfractions", getU8Decoder()],
    ["highInfractions", getU8Decoder()],
    ["lastUpdated", getI64Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

export function getReputationProfileCodec(): FixedSizeCodec<
  ReputationProfileArgs,
  ReputationProfile
> {
  return combineCodec(
    getReputationProfileEncoder(),
    getReputationProfileDecoder(),
  );
}
