/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type ReputationProfile = {
  authority: Address;
  /** Number of reviews received as host */
  hostReviews: number;
  /** Total score from reviews (e.g., sum of ratings) */
  totalScoreHost: bigint;
  /** Number of reviews received as client */
  clientReviews: number;
  /** Total score from reviews (e.g., sum of ratings) */
  totalScoreClient: bigint;
  /** Number of cancellations as host */
  hostCancellations: number;
  /** Number of cancellations as client */
  clientCancellations: number;
  /** Number of reviews skipped as host */
  hostReviewsSkipped: number;
  /** Number of reviews skipped as guest */
  guestReviewsSkipped: number;
  /** Infraction counter */
  lowInfractions: number;
  /** Infraction counter */
  mediumInfractions: number;
  /** Infraction counter */
  highInfractions: number;
  bump: number;
};

export type ReputationProfileArgs = {
  authority: Address;
  /** Number of reviews received as host */
  hostReviews: number;
  /** Total score from reviews (e.g., sum of ratings) */
  totalScoreHost: number | bigint;
  /** Number of reviews received as client */
  clientReviews: number;
  /** Total score from reviews (e.g., sum of ratings) */
  totalScoreClient: number | bigint;
  /** Number of cancellations as host */
  hostCancellations: number;
  /** Number of cancellations as client */
  clientCancellations: number;
  /** Number of reviews skipped as host */
  hostReviewsSkipped: number;
  /** Number of reviews skipped as guest */
  guestReviewsSkipped: number;
  /** Infraction counter */
  lowInfractions: number;
  /** Infraction counter */
  mediumInfractions: number;
  /** Infraction counter */
  highInfractions: number;
  bump: number;
};

export function getReputationProfileEncoder(): FixedSizeEncoder<ReputationProfileArgs> {
  return getStructEncoder([
    ["authority", getAddressEncoder()],
    ["hostReviews", getU32Encoder()],
    ["totalScoreHost", getU64Encoder()],
    ["clientReviews", getU32Encoder()],
    ["totalScoreClient", getU64Encoder()],
    ["hostCancellations", getU32Encoder()],
    ["clientCancellations", getU32Encoder()],
    ["hostReviewsSkipped", getU32Encoder()],
    ["guestReviewsSkipped", getU32Encoder()],
    ["lowInfractions", getU8Encoder()],
    ["mediumInfractions", getU8Encoder()],
    ["highInfractions", getU8Encoder()],
    ["bump", getU8Encoder()],
  ]);
}

export function getReputationProfileDecoder(): FixedSizeDecoder<ReputationProfile> {
  return getStructDecoder([
    ["authority", getAddressDecoder()],
    ["hostReviews", getU32Decoder()],
    ["totalScoreHost", getU64Decoder()],
    ["clientReviews", getU32Decoder()],
    ["totalScoreClient", getU64Decoder()],
    ["hostCancellations", getU32Decoder()],
    ["clientCancellations", getU32Decoder()],
    ["hostReviewsSkipped", getU32Decoder()],
    ["guestReviewsSkipped", getU32Decoder()],
    ["lowInfractions", getU8Decoder()],
    ["mediumInfractions", getU8Decoder()],
    ["highInfractions", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

export function getReputationProfileCodec(): FixedSizeCodec<
  ReputationProfileArgs,
  ReputationProfile
> {
  return combineCodec(
    getReputationProfileEncoder(),
    getReputationProfileDecoder(),
  );
}
