/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getDiscriminatedUnionDecoder,
  getDiscriminatedUnionEncoder,
  getStructDecoder,
  getStructEncoder,
  getUnitDecoder,
  getUnitEncoder,
  type Codec,
  type Decoder,
  type Encoder,
  type GetDiscriminatedUnionVariant,
  type GetDiscriminatedUnionVariantContent,
} from "@solana/kit";
import {
  getPenaltySeverityDecoder,
  getPenaltySeverityEncoder,
  type PenaltySeverity,
  type PenaltySeverityArgs,
} from ".";

export type DisputeOutcome =
  | { __kind: "GuestFavored"; severity: PenaltySeverity }
  | { __kind: "HostFavored"; severity: PenaltySeverity }
  | { __kind: "NoFaultFound" }
  | { __kind: "MaliciousClaim"; severity: PenaltySeverity };

export type DisputeOutcomeArgs =
  | { __kind: "GuestFavored"; severity: PenaltySeverityArgs }
  | { __kind: "HostFavored"; severity: PenaltySeverityArgs }
  | { __kind: "NoFaultFound" }
  | { __kind: "MaliciousClaim"; severity: PenaltySeverityArgs };

export function getDisputeOutcomeEncoder(): Encoder<DisputeOutcomeArgs> {
  return getDiscriminatedUnionEncoder([
    [
      "GuestFavored",
      getStructEncoder([["severity", getPenaltySeverityEncoder()]]),
    ],
    [
      "HostFavored",
      getStructEncoder([["severity", getPenaltySeverityEncoder()]]),
    ],
    ["NoFaultFound", getUnitEncoder()],
    [
      "MaliciousClaim",
      getStructEncoder([["severity", getPenaltySeverityEncoder()]]),
    ],
  ]);
}

export function getDisputeOutcomeDecoder(): Decoder<DisputeOutcome> {
  return getDiscriminatedUnionDecoder([
    [
      "GuestFavored",
      getStructDecoder([["severity", getPenaltySeverityDecoder()]]),
    ],
    [
      "HostFavored",
      getStructDecoder([["severity", getPenaltySeverityDecoder()]]),
    ],
    ["NoFaultFound", getUnitDecoder()],
    [
      "MaliciousClaim",
      getStructDecoder([["severity", getPenaltySeverityDecoder()]]),
    ],
  ]);
}

export function getDisputeOutcomeCodec(): Codec<
  DisputeOutcomeArgs,
  DisputeOutcome
> {
  return combineCodec(getDisputeOutcomeEncoder(), getDisputeOutcomeDecoder());
}

// Data Enum Helpers.
export function disputeOutcome(
  kind: "GuestFavored",
  data: GetDiscriminatedUnionVariantContent<
    DisputeOutcomeArgs,
    "__kind",
    "GuestFavored"
  >,
): GetDiscriminatedUnionVariant<DisputeOutcomeArgs, "__kind", "GuestFavored">;
export function disputeOutcome(
  kind: "HostFavored",
  data: GetDiscriminatedUnionVariantContent<
    DisputeOutcomeArgs,
    "__kind",
    "HostFavored"
  >,
): GetDiscriminatedUnionVariant<DisputeOutcomeArgs, "__kind", "HostFavored">;
export function disputeOutcome(
  kind: "NoFaultFound",
): GetDiscriminatedUnionVariant<DisputeOutcomeArgs, "__kind", "NoFaultFound">;
export function disputeOutcome(
  kind: "MaliciousClaim",
  data: GetDiscriminatedUnionVariantContent<
    DisputeOutcomeArgs,
    "__kind",
    "MaliciousClaim"
  >,
): GetDiscriminatedUnionVariant<DisputeOutcomeArgs, "__kind", "MaliciousClaim">;
export function disputeOutcome<K extends DisputeOutcomeArgs["__kind"], Data>(
  kind: K,
  data?: Data,
) {
  return Array.isArray(data)
    ? { __kind: kind, fields: data }
    : { __kind: kind, ...(data ?? {}) };
}

export function isDisputeOutcome<K extends DisputeOutcome["__kind"]>(
  kind: K,
  value: DisputeOutcome,
): value is DisputeOutcome & { __kind: K } {
  return value.__kind === kind;
}
