/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type Listing = {
  listingId: number;
  totalReviews: bigint;
  rating: bigint;
  price: bigint;
  isActive: boolean;
  isOccupied: boolean;
  stateHash: ReadonlyUint8Array;
  /**
   * Arweave transaction ID (32 bytes, Base64url-encoded off-chain).
   * Backend URL
   * IPFS CID v1
   * Resolves to: https://arweave.net/{base64url(arweave_tx_id)}
   */
  contentRef: ReadonlyUint8Array;
  bump: number;
};

export type ListingArgs = {
  listingId: number;
  totalReviews: number | bigint;
  rating: number | bigint;
  price: number | bigint;
  isActive: boolean;
  isOccupied: boolean;
  stateHash: ReadonlyUint8Array;
  /**
   * Arweave transaction ID (32 bytes, Base64url-encoded off-chain).
   * Backend URL
   * IPFS CID v1
   * Resolves to: https://arweave.net/{base64url(arweave_tx_id)}
   */
  contentRef: ReadonlyUint8Array;
  bump: number;
};

export function getListingEncoder(): FixedSizeEncoder<ListingArgs> {
  return getStructEncoder([
    ["listingId", getU16Encoder()],
    ["totalReviews", getU64Encoder()],
    ["rating", getU64Encoder()],
    ["price", getU64Encoder()],
    ["isActive", getBooleanEncoder()],
    ["isOccupied", getBooleanEncoder()],
    ["stateHash", fixEncoderSize(getBytesEncoder(), 32)],
    ["contentRef", fixEncoderSize(getBytesEncoder(), 32)],
    ["bump", getU8Encoder()],
  ]);
}

export function getListingDecoder(): FixedSizeDecoder<Listing> {
  return getStructDecoder([
    ["listingId", getU16Decoder()],
    ["totalReviews", getU64Decoder()],
    ["rating", getU64Decoder()],
    ["price", getU64Decoder()],
    ["isActive", getBooleanDecoder()],
    ["isOccupied", getBooleanDecoder()],
    ["stateHash", fixDecoderSize(getBytesDecoder(), 32)],
    ["contentRef", fixDecoderSize(getBytesDecoder(), 32)],
    ["bump", getU8Decoder()],
  ]);
}

export function getListingCodec(): FixedSizeCodec<ListingArgs, Listing> {
  return combineCodec(getListingEncoder(), getListingDecoder());
}
