/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STAYKE_CORE_PROGRAM_ADDRESS } from "../programs";
import {
  getPenaltySeverityDecoder,
  getPenaltySeverityEncoder,
  type PenaltySeverity,
  type PenaltySeverityArgs,
} from "../types";

export const ADD_INFRACTION_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  238, 116, 210, 154, 186, 175, 136, 151,
]);

export function getAddInfractionDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ADD_INFRACTION_DISCRIMINATOR,
  );
}

export type AddInfractionInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountReputationProfile extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountReputationProfile extends string
        ? WritableAccount<TAccountReputationProfile>
        : TAccountReputationProfile,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountCpiAuthority extends string
        ? ReadonlySignerAccount<TAccountCpiAuthority> &
            AccountSignerMeta<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type AddInfractionInstructionData = {
  discriminator: ReadonlyUint8Array;
  severity: PenaltySeverity;
};

export type AddInfractionInstructionDataArgs = {
  severity: PenaltySeverityArgs;
};

export function getAddInfractionInstructionDataEncoder(): FixedSizeEncoder<AddInfractionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["severity", getPenaltySeverityEncoder()],
    ]),
    (value) => ({ ...value, discriminator: ADD_INFRACTION_DISCRIMINATOR }),
  );
}

export function getAddInfractionInstructionDataDecoder(): FixedSizeDecoder<AddInfractionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["severity", getPenaltySeverityDecoder()],
  ]);
}

export function getAddInfractionInstructionDataCodec(): FixedSizeCodec<
  AddInfractionInstructionDataArgs,
  AddInfractionInstructionData
> {
  return combineCodec(
    getAddInfractionInstructionDataEncoder(),
    getAddInfractionInstructionDataDecoder(),
  );
}

export type AddInfractionAsyncInput<
  TAccountReputationProfile extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  reputationProfile: Address<TAccountReputationProfile>;
  globalConfig?: Address<TAccountGlobalConfig>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  severity: AddInfractionInstructionDataArgs["severity"];
};

export async function getAddInfractionInstructionAsync<
  TAccountReputationProfile extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: AddInfractionAsyncInput<
    TAccountReputationProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AddInfractionInstruction<
    TProgramAddress,
    TAccountReputationProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    reputationProfile: {
      value: input.reputationProfile ?? null,
      isWritable: true,
    },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "29A2HXuDHX8WQoPnYbFP4DR4W6HjQTBDA2N5pCPZEFs4" as Address<"29A2HXuDHX8WQoPnYbFP4DR4W6HjQTBDA2N5pCPZEFs4">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("reputationProfile", accounts.reputationProfile),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getAddInfractionInstructionDataEncoder().encode(
      args as AddInfractionInstructionDataArgs,
    ),
    programAddress,
  } as AddInfractionInstruction<
    TProgramAddress,
    TAccountReputationProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type AddInfractionInput<
  TAccountReputationProfile extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  reputationProfile: Address<TAccountReputationProfile>;
  globalConfig: Address<TAccountGlobalConfig>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  severity: AddInfractionInstructionDataArgs["severity"];
};

export function getAddInfractionInstruction<
  TAccountReputationProfile extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: AddInfractionInput<
    TAccountReputationProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): AddInfractionInstruction<
  TProgramAddress,
  TAccountReputationProfile,
  TAccountGlobalConfig,
  TAccountCpiAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    reputationProfile: {
      value: input.reputationProfile ?? null,
      isWritable: true,
    },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("reputationProfile", accounts.reputationProfile),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getAddInfractionInstructionDataEncoder().encode(
      args as AddInfractionInstructionDataArgs,
    ),
    programAddress,
  } as AddInfractionInstruction<
    TProgramAddress,
    TAccountReputationProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type ParsedAddInfractionInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    reputationProfile: TAccountMetas[0];
    globalConfig: TAccountMetas[1];
    cpiAuthority: TAccountMetas[2];
  };
  data: AddInfractionInstructionData;
};

export function parseAddInfractionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAddInfractionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      reputationProfile: getNextAccount(),
      globalConfig: getNextAccount(),
      cpiAuthority: getNextAccount(),
    },
    data: getAddInfractionInstructionDataDecoder().decode(instruction.data),
  };
}
