/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STAYKE_CORE_PROGRAM_ADDRESS } from "../programs";

export const CLEAR_LISTING_BOOKING_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([115, 33, 218, 127, 147, 182, 108, 120]);

export function getClearListingBookingDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLEAR_LISTING_BOOKING_DISCRIMINATOR,
  );
}

export type ClearListingBookingInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountUserProfile extends string | AccountMeta<string> = string,
  TAccountListing extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUserProfile extends string
        ? ReadonlyAccount<TAccountUserProfile>
        : TAccountUserProfile,
      TAccountListing extends string
        ? WritableAccount<TAccountListing>
        : TAccountListing,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountCpiAuthority extends string
        ? ReadonlySignerAccount<TAccountCpiAuthority> &
            AccountSignerMeta<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type ClearListingBookingInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ClearListingBookingInstructionDataArgs = {};

export function getClearListingBookingInstructionDataEncoder(): FixedSizeEncoder<ClearListingBookingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: CLEAR_LISTING_BOOKING_DISCRIMINATOR,
    }),
  );
}

export function getClearListingBookingInstructionDataDecoder(): FixedSizeDecoder<ClearListingBookingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClearListingBookingInstructionDataCodec(): FixedSizeCodec<
  ClearListingBookingInstructionDataArgs,
  ClearListingBookingInstructionData
> {
  return combineCodec(
    getClearListingBookingInstructionDataEncoder(),
    getClearListingBookingInstructionDataDecoder(),
  );
}

export type ClearListingBookingAsyncInput<
  TAccountUserProfile extends string = string,
  TAccountListing extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  userProfile: Address<TAccountUserProfile>;
  listing: Address<TAccountListing>;
  globalConfig?: Address<TAccountGlobalConfig>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
};

export async function getClearListingBookingInstructionAsync<
  TAccountUserProfile extends string,
  TAccountListing extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: ClearListingBookingAsyncInput<
    TAccountUserProfile,
    TAccountListing,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ClearListingBookingInstruction<
    TProgramAddress,
    TAccountUserProfile,
    TAccountListing,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    userProfile: { value: input.userProfile ?? null, isWritable: false },
    listing: { value: input.listing ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW" as Address<"2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("userProfile", accounts.userProfile),
      getAccountMeta("listing", accounts.listing),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getClearListingBookingInstructionDataEncoder().encode({}),
    programAddress,
  } as ClearListingBookingInstruction<
    TProgramAddress,
    TAccountUserProfile,
    TAccountListing,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type ClearListingBookingInput<
  TAccountUserProfile extends string = string,
  TAccountListing extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  userProfile: Address<TAccountUserProfile>;
  listing: Address<TAccountListing>;
  globalConfig: Address<TAccountGlobalConfig>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
};

export function getClearListingBookingInstruction<
  TAccountUserProfile extends string,
  TAccountListing extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: ClearListingBookingInput<
    TAccountUserProfile,
    TAccountListing,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): ClearListingBookingInstruction<
  TProgramAddress,
  TAccountUserProfile,
  TAccountListing,
  TAccountGlobalConfig,
  TAccountCpiAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    userProfile: { value: input.userProfile ?? null, isWritable: false },
    listing: { value: input.listing ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("userProfile", accounts.userProfile),
      getAccountMeta("listing", accounts.listing),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getClearListingBookingInstructionDataEncoder().encode({}),
    programAddress,
  } as ClearListingBookingInstruction<
    TProgramAddress,
    TAccountUserProfile,
    TAccountListing,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type ParsedClearListingBookingInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    userProfile: TAccountMetas[0];
    listing: TAccountMetas[1];
    globalConfig: TAccountMetas[2];
    cpiAuthority: TAccountMetas[3];
  };
  data: ClearListingBookingInstructionData;
};

export function parseClearListingBookingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClearListingBookingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      userProfile: getNextAccount(),
      listing: getNextAccount(),
      globalConfig: getNextAccount(),
      cpiAuthority: getNextAccount(),
    },
    data: getClearListingBookingInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
