/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STAYKE_CORE_PROGRAM_ADDRESS } from "../programs";

export const SET_ACTIVE_BOOKING_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([41, 169, 14, 125, 137, 76, 11, 170]);

export function getSetActiveBookingDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    SET_ACTIVE_BOOKING_DISCRIMINATOR,
  );
}

export type SetActiveBookingInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountUserProfile extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUserProfile extends string
        ? WritableAccount<TAccountUserProfile>
        : TAccountUserProfile,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountCpiAuthority extends string
        ? ReadonlySignerAccount<TAccountCpiAuthority> &
            AccountSignerMeta<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type SetActiveBookingInstructionData = {
  discriminator: ReadonlyUint8Array;
  booking: Address;
};

export type SetActiveBookingInstructionDataArgs = { booking: Address };

export function getSetActiveBookingInstructionDataEncoder(): FixedSizeEncoder<SetActiveBookingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["booking", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_ACTIVE_BOOKING_DISCRIMINATOR }),
  );
}

export function getSetActiveBookingInstructionDataDecoder(): FixedSizeDecoder<SetActiveBookingInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["booking", getAddressDecoder()],
  ]);
}

export function getSetActiveBookingInstructionDataCodec(): FixedSizeCodec<
  SetActiveBookingInstructionDataArgs,
  SetActiveBookingInstructionData
> {
  return combineCodec(
    getSetActiveBookingInstructionDataEncoder(),
    getSetActiveBookingInstructionDataDecoder(),
  );
}

export type SetActiveBookingAsyncInput<
  TAccountUserProfile extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  userProfile: Address<TAccountUserProfile>;
  globalConfig?: Address<TAccountGlobalConfig>;
  /** CPI authority PDA of an allowlisted Stayke program. */
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  booking: SetActiveBookingInstructionDataArgs["booking"];
};

export async function getSetActiveBookingInstructionAsync<
  TAccountUserProfile extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: SetActiveBookingAsyncInput<
    TAccountUserProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SetActiveBookingInstruction<
    TProgramAddress,
    TAccountUserProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    userProfile: { value: input.userProfile ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("userProfile", accounts.userProfile),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getSetActiveBookingInstructionDataEncoder().encode(
      args as SetActiveBookingInstructionDataArgs,
    ),
    programAddress,
  } as SetActiveBookingInstruction<
    TProgramAddress,
    TAccountUserProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type SetActiveBookingInput<
  TAccountUserProfile extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  userProfile: Address<TAccountUserProfile>;
  globalConfig: Address<TAccountGlobalConfig>;
  /** CPI authority PDA of an allowlisted Stayke program. */
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  booking: SetActiveBookingInstructionDataArgs["booking"];
};

export function getSetActiveBookingInstruction<
  TAccountUserProfile extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: SetActiveBookingInput<
    TAccountUserProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): SetActiveBookingInstruction<
  TProgramAddress,
  TAccountUserProfile,
  TAccountGlobalConfig,
  TAccountCpiAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    userProfile: { value: input.userProfile ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("userProfile", accounts.userProfile),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getSetActiveBookingInstructionDataEncoder().encode(
      args as SetActiveBookingInstructionDataArgs,
    ),
    programAddress,
  } as SetActiveBookingInstruction<
    TProgramAddress,
    TAccountUserProfile,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type ParsedSetActiveBookingInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    userProfile: TAccountMetas[0];
    globalConfig: TAccountMetas[1];
    /** CPI authority PDA of an allowlisted Stayke program. */
    cpiAuthority: TAccountMetas[2];
  };
  data: SetActiveBookingInstructionData;
};

export function parseSetActiveBookingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetActiveBookingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      userProfile: getNextAccount(),
      globalConfig: getNextAccount(),
      cpiAuthority: getNextAccount(),
    },
    data: getSetActiveBookingInstructionDataDecoder().decode(instruction.data),
  };
}
