/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findUserProfilePda } from "../pdas";
import { STAYKE_CORE_PROGRAM_ADDRESS } from "../programs";

export const UPDATE_LISTING_PUBLISH_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([168, 202, 247, 130, 113, 8, 109, 99]);

export function getUpdateListingPublishDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_LISTING_PUBLISH_DISCRIMINATOR,
  );
}

export type UpdateListingPublishInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountUserProfile extends string | AccountMeta<string> = string,
  TAccountListing extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountPayer extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUserProfile extends string
        ? ReadonlyAccount<TAccountUserProfile>
        : TAccountUserProfile,
      TAccountListing extends string
        ? WritableAccount<TAccountListing>
        : TAccountListing,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateListingPublishInstructionData = {
  discriminator: ReadonlyUint8Array;
  active: boolean;
};

export type UpdateListingPublishInstructionDataArgs = { active: boolean };

export function getUpdateListingPublishInstructionDataEncoder(): FixedSizeEncoder<UpdateListingPublishInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["active", getBooleanEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_LISTING_PUBLISH_DISCRIMINATOR,
    }),
  );
}

export function getUpdateListingPublishInstructionDataDecoder(): FixedSizeDecoder<UpdateListingPublishInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["active", getBooleanDecoder()],
  ]);
}

export function getUpdateListingPublishInstructionDataCodec(): FixedSizeCodec<
  UpdateListingPublishInstructionDataArgs,
  UpdateListingPublishInstructionData
> {
  return combineCodec(
    getUpdateListingPublishInstructionDataEncoder(),
    getUpdateListingPublishInstructionDataDecoder(),
  );
}

export type UpdateListingPublishAsyncInput<
  TAccountUserProfile extends string = string,
  TAccountListing extends string = string,
  TAccountAuthority extends string = string,
  TAccountPayer extends string = string,
> = {
  userProfile?: Address<TAccountUserProfile>;
  listing: Address<TAccountListing>;
  authority: TransactionSigner<TAccountAuthority>;
  payer: TransactionSigner<TAccountPayer>;
  active: UpdateListingPublishInstructionDataArgs["active"];
};

export async function getUpdateListingPublishInstructionAsync<
  TAccountUserProfile extends string,
  TAccountListing extends string,
  TAccountAuthority extends string,
  TAccountPayer extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: UpdateListingPublishAsyncInput<
    TAccountUserProfile,
    TAccountListing,
    TAccountAuthority,
    TAccountPayer
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdateListingPublishInstruction<
    TProgramAddress,
    TAccountUserProfile,
    TAccountListing,
    TAccountAuthority,
    TAccountPayer
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    userProfile: { value: input.userProfile ?? null, isWritable: false },
    listing: { value: input.listing ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.userProfile.value) {
    accounts.userProfile.value = await findUserProfilePda({
      authority: getAddressFromResolvedInstructionAccount(
        "authority",
        accounts.authority.value,
      ),
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("userProfile", accounts.userProfile),
      getAccountMeta("listing", accounts.listing),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("payer", accounts.payer),
    ],
    data: getUpdateListingPublishInstructionDataEncoder().encode(
      args as UpdateListingPublishInstructionDataArgs,
    ),
    programAddress,
  } as UpdateListingPublishInstruction<
    TProgramAddress,
    TAccountUserProfile,
    TAccountListing,
    TAccountAuthority,
    TAccountPayer
  >);
}

export type UpdateListingPublishInput<
  TAccountUserProfile extends string = string,
  TAccountListing extends string = string,
  TAccountAuthority extends string = string,
  TAccountPayer extends string = string,
> = {
  userProfile: Address<TAccountUserProfile>;
  listing: Address<TAccountListing>;
  authority: TransactionSigner<TAccountAuthority>;
  payer: TransactionSigner<TAccountPayer>;
  active: UpdateListingPublishInstructionDataArgs["active"];
};

export function getUpdateListingPublishInstruction<
  TAccountUserProfile extends string,
  TAccountListing extends string,
  TAccountAuthority extends string,
  TAccountPayer extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: UpdateListingPublishInput<
    TAccountUserProfile,
    TAccountListing,
    TAccountAuthority,
    TAccountPayer
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateListingPublishInstruction<
  TProgramAddress,
  TAccountUserProfile,
  TAccountListing,
  TAccountAuthority,
  TAccountPayer
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    userProfile: { value: input.userProfile ?? null, isWritable: false },
    listing: { value: input.listing ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("userProfile", accounts.userProfile),
      getAccountMeta("listing", accounts.listing),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("payer", accounts.payer),
    ],
    data: getUpdateListingPublishInstructionDataEncoder().encode(
      args as UpdateListingPublishInstructionDataArgs,
    ),
    programAddress,
  } as UpdateListingPublishInstruction<
    TProgramAddress,
    TAccountUserProfile,
    TAccountListing,
    TAccountAuthority,
    TAccountPayer
  >);
}

export type ParsedUpdateListingPublishInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    userProfile: TAccountMetas[0];
    listing: TAccountMetas[1];
    authority: TAccountMetas[2];
    payer: TAccountMetas[3];
  };
  data: UpdateListingPublishInstructionData;
};

export function parseUpdateListingPublishInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateListingPublishInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      userProfile: getNextAccount(),
      listing: getNextAccount(),
      authority: getNextAccount(),
      payer: getNextAccount(),
    },
    data: getUpdateListingPublishInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
