/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STAYKE_CORE_PROGRAM_ADDRESS } from "../programs";

export const UPDATE_CLIENT_REVIEW_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([25, 243, 175, 86, 13, 118, 223, 101]);

export function getUpdateClientReviewDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_CLIENT_REVIEW_DISCRIMINATOR,
  );
}

export type UpdateClientReviewInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountClientProfile extends string | AccountMeta<string> = string,
  TAccountClientReputation extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountClientProfile extends string
        ? ReadonlyAccount<TAccountClientProfile>
        : TAccountClientProfile,
      TAccountClientReputation extends string
        ? WritableAccount<TAccountClientReputation>
        : TAccountClientReputation,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountCpiAuthority extends string
        ? ReadonlySignerAccount<TAccountCpiAuthority> &
            AccountSignerMeta<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateClientReviewInstructionData = {
  discriminator: ReadonlyUint8Array;
  score: number;
};

export type UpdateClientReviewInstructionDataArgs = { score: number };

export function getUpdateClientReviewInstructionDataEncoder(): FixedSizeEncoder<UpdateClientReviewInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["score", getU8Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_CLIENT_REVIEW_DISCRIMINATOR,
    }),
  );
}

export function getUpdateClientReviewInstructionDataDecoder(): FixedSizeDecoder<UpdateClientReviewInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["score", getU8Decoder()],
  ]);
}

export function getUpdateClientReviewInstructionDataCodec(): FixedSizeCodec<
  UpdateClientReviewInstructionDataArgs,
  UpdateClientReviewInstructionData
> {
  return combineCodec(
    getUpdateClientReviewInstructionDataEncoder(),
    getUpdateClientReviewInstructionDataDecoder(),
  );
}

export type UpdateClientReviewAsyncInput<
  TAccountClientProfile extends string = string,
  TAccountClientReputation extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  clientProfile: Address<TAccountClientProfile>;
  clientReputation: Address<TAccountClientReputation>;
  globalConfig?: Address<TAccountGlobalConfig>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  score: UpdateClientReviewInstructionDataArgs["score"];
};

export async function getUpdateClientReviewInstructionAsync<
  TAccountClientProfile extends string,
  TAccountClientReputation extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: UpdateClientReviewAsyncInput<
    TAccountClientProfile,
    TAccountClientReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdateClientReviewInstruction<
    TProgramAddress,
    TAccountClientProfile,
    TAccountClientReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    clientProfile: { value: input.clientProfile ?? null, isWritable: false },
    clientReputation: {
      value: input.clientReputation ?? null,
      isWritable: true,
    },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT" as Address<"9ESE5Ztpr8zWbLyXCyiB5QqcjxHghotT8zqJxD2S3zaT">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("clientProfile", accounts.clientProfile),
      getAccountMeta("clientReputation", accounts.clientReputation),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getUpdateClientReviewInstructionDataEncoder().encode(
      args as UpdateClientReviewInstructionDataArgs,
    ),
    programAddress,
  } as UpdateClientReviewInstruction<
    TProgramAddress,
    TAccountClientProfile,
    TAccountClientReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type UpdateClientReviewInput<
  TAccountClientProfile extends string = string,
  TAccountClientReputation extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  clientProfile: Address<TAccountClientProfile>;
  clientReputation: Address<TAccountClientReputation>;
  globalConfig: Address<TAccountGlobalConfig>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  score: UpdateClientReviewInstructionDataArgs["score"];
};

export function getUpdateClientReviewInstruction<
  TAccountClientProfile extends string,
  TAccountClientReputation extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: UpdateClientReviewInput<
    TAccountClientProfile,
    TAccountClientReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateClientReviewInstruction<
  TProgramAddress,
  TAccountClientProfile,
  TAccountClientReputation,
  TAccountGlobalConfig,
  TAccountCpiAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    clientProfile: { value: input.clientProfile ?? null, isWritable: false },
    clientReputation: {
      value: input.clientReputation ?? null,
      isWritable: true,
    },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("clientProfile", accounts.clientProfile),
      getAccountMeta("clientReputation", accounts.clientReputation),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getUpdateClientReviewInstructionDataEncoder().encode(
      args as UpdateClientReviewInstructionDataArgs,
    ),
    programAddress,
  } as UpdateClientReviewInstruction<
    TProgramAddress,
    TAccountClientProfile,
    TAccountClientReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type ParsedUpdateClientReviewInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    clientProfile: TAccountMetas[0];
    clientReputation: TAccountMetas[1];
    globalConfig: TAccountMetas[2];
    cpiAuthority: TAccountMetas[3];
  };
  data: UpdateClientReviewInstructionData;
};

export function parseUpdateClientReviewInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateClientReviewInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      clientProfile: getNextAccount(),
      clientReputation: getNextAccount(),
      globalConfig: getNextAccount(),
      cpiAuthority: getNextAccount(),
    },
    data: getUpdateClientReviewInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
