/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STAYKE_CORE_PROGRAM_ADDRESS } from "../programs";

export const UPDATE_HOST_REVIEW_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([103, 62, 206, 90, 68, 110, 101, 85]);

export function getUpdateHostReviewDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_HOST_REVIEW_DISCRIMINATOR,
  );
}

export type UpdateHostReviewInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountHostProfile extends string | AccountMeta<string> = string,
  TAccountHostReputation extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountCpiAuthority extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountHostProfile extends string
        ? WritableAccount<TAccountHostProfile>
        : TAccountHostProfile,
      TAccountHostReputation extends string
        ? WritableAccount<TAccountHostReputation>
        : TAccountHostReputation,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountCpiAuthority extends string
        ? ReadonlySignerAccount<TAccountCpiAuthority> &
            AccountSignerMeta<TAccountCpiAuthority>
        : TAccountCpiAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateHostReviewInstructionData = {
  discriminator: ReadonlyUint8Array;
  score: number;
};

export type UpdateHostReviewInstructionDataArgs = { score: number };

export function getUpdateHostReviewInstructionDataEncoder(): FixedSizeEncoder<UpdateHostReviewInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["score", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_HOST_REVIEW_DISCRIMINATOR }),
  );
}

export function getUpdateHostReviewInstructionDataDecoder(): FixedSizeDecoder<UpdateHostReviewInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["score", getU8Decoder()],
  ]);
}

export function getUpdateHostReviewInstructionDataCodec(): FixedSizeCodec<
  UpdateHostReviewInstructionDataArgs,
  UpdateHostReviewInstructionData
> {
  return combineCodec(
    getUpdateHostReviewInstructionDataEncoder(),
    getUpdateHostReviewInstructionDataDecoder(),
  );
}

export type UpdateHostReviewAsyncInput<
  TAccountHostProfile extends string = string,
  TAccountHostReputation extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  hostProfile: Address<TAccountHostProfile>;
  hostReputation: Address<TAccountHostReputation>;
  globalConfig?: Address<TAccountGlobalConfig>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  score: UpdateHostReviewInstructionDataArgs["score"];
};

export async function getUpdateHostReviewInstructionAsync<
  TAccountHostProfile extends string,
  TAccountHostReputation extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: UpdateHostReviewAsyncInput<
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdateHostReviewInstruction<
    TProgramAddress,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    hostProfile: { value: input.hostProfile ?? null, isWritable: true },
    hostReputation: { value: input.hostReputation ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress:
        "2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW" as Address<"2GM2yLmDtz2Hyb8T5VBftERmiyJ5whKUmv6V4hBjNXMW">,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            103, 108, 111, 98, 97, 108, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("hostReputation", accounts.hostReputation),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getUpdateHostReviewInstructionDataEncoder().encode(
      args as UpdateHostReviewInstructionDataArgs,
    ),
    programAddress,
  } as UpdateHostReviewInstruction<
    TProgramAddress,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type UpdateHostReviewInput<
  TAccountHostProfile extends string = string,
  TAccountHostReputation extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountCpiAuthority extends string = string,
> = {
  hostProfile: Address<TAccountHostProfile>;
  hostReputation: Address<TAccountHostReputation>;
  globalConfig: Address<TAccountGlobalConfig>;
  cpiAuthority: TransactionSigner<TAccountCpiAuthority>;
  score: UpdateHostReviewInstructionDataArgs["score"];
};

export function getUpdateHostReviewInstruction<
  TAccountHostProfile extends string,
  TAccountHostReputation extends string,
  TAccountGlobalConfig extends string,
  TAccountCpiAuthority extends string,
  TProgramAddress extends Address = typeof STAYKE_CORE_PROGRAM_ADDRESS,
>(
  input: UpdateHostReviewInput<
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateHostReviewInstruction<
  TProgramAddress,
  TAccountHostProfile,
  TAccountHostReputation,
  TAccountGlobalConfig,
  TAccountCpiAuthority
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAYKE_CORE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    hostProfile: { value: input.hostProfile ?? null, isWritable: true },
    hostReputation: { value: input.hostReputation ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    cpiAuthority: { value: input.cpiAuthority ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("hostProfile", accounts.hostProfile),
      getAccountMeta("hostReputation", accounts.hostReputation),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("cpiAuthority", accounts.cpiAuthority),
    ],
    data: getUpdateHostReviewInstructionDataEncoder().encode(
      args as UpdateHostReviewInstructionDataArgs,
    ),
    programAddress,
  } as UpdateHostReviewInstruction<
    TProgramAddress,
    TAccountHostProfile,
    TAccountHostReputation,
    TAccountGlobalConfig,
    TAccountCpiAuthority
  >);
}

export type ParsedUpdateHostReviewInstruction<
  TProgram extends string = typeof STAYKE_CORE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    hostProfile: TAccountMetas[0];
    hostReputation: TAccountMetas[1];
    globalConfig: TAccountMetas[2];
    cpiAuthority: TAccountMetas[3];
  };
  data: UpdateHostReviewInstructionData;
};

export function parseUpdateHostReviewInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateHostReviewInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      hostProfile: getNextAccount(),
      hostReputation: getNextAccount(),
      globalConfig: getNextAccount(),
      cpiAuthority: getNextAccount(),
    },
    data: getUpdateHostReviewInstructionDataDecoder().decode(instruction.data),
  };
}
