/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getAddressEncoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getU16Encoder,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type ListingSeeds = {
  userProfile: Address;
  listingId: number;
};

export async function findListingPda(
  seeds: ListingSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP" as Address<"8yHjmyUgA9x4pzftX1cwJt8SnG8iV1zxLjEP77HKc9YP">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([108, 105, 115, 116, 105, 110, 103]),
      ),
      getAddressEncoder().encode(seeds.userProfile),
      getU16Encoder().encode(seeds.listingId),
    ],
  });
}
