/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const USER_PROFILE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  32, 37, 119, 205, 179, 180, 13, 194,
]);

export function getUserProfileDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    USER_PROFILE_DISCRIMINATOR,
  );
}

export type UserProfile = {
  discriminator: ReadonlyUint8Array;
  authority: Address;
  /** Identity pubkey linked to IdentityAccount */
  identity: Option<Address>;
  /** Refers to the active booking paid by the user */
  activeBooking: Option<Address>;
  /** This field represents the total amount of tokens that the user has deposited in the platform, excluding the ones that are currently being used for lending and staking. */
  deposited: bigint;
  /** This field represents the total amount of tokens that the user has lent */
  lending: bigint;
  /** This field represents the amount of liquid staked tokens that the user has. */
  staked: bigint;
  /** This might be deleted in the future, but for now I think it's better to have it here so we don't call identity account every time we need to check if the user is banned or not. */
  banned: boolean;
  /** Counter for the amount of listings that the user has created, this is used to generate the listing_id for each listing created by the user. */
  listings: number;
  /** Number of stays hosted */
  hostedStays: number;
  /** Number of stays completed as a guest */
  completedStays: number;
  bump: number;
};

export type UserProfileArgs = {
  authority: Address;
  /** Identity pubkey linked to IdentityAccount */
  identity: OptionOrNullable<Address>;
  /** Refers to the active booking paid by the user */
  activeBooking: OptionOrNullable<Address>;
  /** This field represents the total amount of tokens that the user has deposited in the platform, excluding the ones that are currently being used for lending and staking. */
  deposited: number | bigint;
  /** This field represents the total amount of tokens that the user has lent */
  lending: number | bigint;
  /** This field represents the amount of liquid staked tokens that the user has. */
  staked: number | bigint;
  /** This might be deleted in the future, but for now I think it's better to have it here so we don't call identity account every time we need to check if the user is banned or not. */
  banned: boolean;
  /** Counter for the amount of listings that the user has created, this is used to generate the listing_id for each listing created by the user. */
  listings: number;
  /** Number of stays hosted */
  hostedStays: number;
  /** Number of stays completed as a guest */
  completedStays: number;
  bump: number;
};

/** Gets the encoder for {@link UserProfileArgs} account data. */
export function getUserProfileEncoder(): Encoder<UserProfileArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["authority", getAddressEncoder()],
      ["identity", getOptionEncoder(getAddressEncoder())],
      ["activeBooking", getOptionEncoder(getAddressEncoder())],
      ["deposited", getU64Encoder()],
      ["lending", getU64Encoder()],
      ["staked", getU64Encoder()],
      ["banned", getBooleanEncoder()],
      ["listings", getU16Encoder()],
      ["hostedStays", getU32Encoder()],
      ["completedStays", getU32Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: USER_PROFILE_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link UserProfile} account data. */
export function getUserProfileDecoder(): Decoder<UserProfile> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["authority", getAddressDecoder()],
    ["identity", getOptionDecoder(getAddressDecoder())],
    ["activeBooking", getOptionDecoder(getAddressDecoder())],
    ["deposited", getU64Decoder()],
    ["lending", getU64Decoder()],
    ["staked", getU64Decoder()],
    ["banned", getBooleanDecoder()],
    ["listings", getU16Decoder()],
    ["hostedStays", getU32Decoder()],
    ["completedStays", getU32Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link UserProfile} account data. */
export function getUserProfileCodec(): Codec<UserProfileArgs, UserProfile> {
  return combineCodec(getUserProfileEncoder(), getUserProfileDecoder());
}

export function decodeUserProfile<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<UserProfile, TAddress>;
export function decodeUserProfile<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<UserProfile, TAddress>;
export function decodeUserProfile<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<UserProfile, TAddress> | MaybeAccount<UserProfile, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getUserProfileDecoder(),
  );
}

export async function fetchUserProfile<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<UserProfile, TAddress>> {
  const maybeAccount = await fetchMaybeUserProfile(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeUserProfile<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<UserProfile, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeUserProfile(maybeAccount);
}

export async function fetchAllUserProfile(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<UserProfile>[]> {
  const maybeAccounts = await fetchAllMaybeUserProfile(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeUserProfile(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<UserProfile>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeUserProfile(maybeAccount));
}
